(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
<<LieART`
Print["Lie Algebras v0.3 by Yiwen Pan"]


(* ::Input::Initialization:: *)
(* make ready some basic quantities *)
GetAlgebra[g_]:=Module[{$a,sols},
\[ScriptG]=g;
rankg=Rank[g];
simpleRoots=OrthogonalSimpleRoots[g]//OmegaBasis;

simpleCoRoots=Table[(2simpleRoots[[i]])/ScalarProduct[simpleRoots[[i]],simpleRoots[[i]]],{i,rankg}];
positiveRoots=PositiveRoots[g];
roots=positiveRoots~Join~(-positiveRoots);

fundamentalWeights=OrthogonalFundamentalWeights[g]//OmegaBasis;
sols=Table[ScalarProduct[Sum[$a[i][ip]fundamentalWeights[[ip]],{ip,rankg}],simpleRoots[[j]]]==KroneckerDelta[i,j],{j,rankg},{i,rankg}]//Simplify//Flatten//Solve;
fundamentalCoWeights=Table[Sum[$a[i][j]fundamentalWeights[[j]],{j,rankg}],{i,rankg}]/.sols[[1]];

highestRoot=HighestRoot[g];
WeylVector=1/2 Total[positiveRoots];
\[Rho]=WeylVector;

zeroWeight=0fundamentalWeights[[1]];

dimg=2NumberOfPositiveRoots[g]+rankg;

coMarks=Table[ScalarProduct[highestRoot,fundamentalWeights[[i]]],{i,rankg}];
hcheck=Total[coMarks]+1;


Clear[K];
K[II_/;II\[Element]Integers,JJ_\[Element]Integers]:=IdentityMatrix[rankg][[II,JJ]];
K[\[Alpha]_,\[Beta]_]:=0/;!TrueQ[\[Alpha]+\[Beta]==RootOmega[Head[\[ScriptG]][[1]]][0,0]];
K[\[Alpha]_,\[Beta]_]:=2/ScalarProduct[\[Alpha],\[Alpha]]/;TrueQ[\[Alpha]+\[Beta]==RootOmega[Head[\[ScriptG]][[1]]][0,0]];
];


(* ::Input::Initialization:: *)



(* ::Input::Initialization:: *)
Clear[GetAffineAlgebra]
GetAffineAlgebra[g_:A2]:=Module[{},
Clear[SimpleAffineRoot,FundamentalAffineWeight,rankAffineg];
GetAlgebra[g];
rankAffineg=Rank[g]+1;
(* Subscript[Overscript[\[Alpha], ^], 0], Subscript[Overscript[\[Alpha], ^], i] *)
SimpleAffineRoot[0]={-highestRoot,0,1};
SimpleAffineRoot[i_]:={simpleRoots[[i]],0,0};
finiteAffineRoots=Table[{\[Alpha],0,0},{\[Alpha],roots}];
(* Subscript[Overscript[\[Omega], ^], 0], Subscript[Overscript[\[Omega], ^], i] *)
FundamentalAffineWeight[0]={zeroWeight,1,0};
FundamentalAffineWeight[i_]:={fundamentalWeights[[i]],coMarks[[i]],0};
fundamentalAffineWeights=Table[FundamentalAffineWeight[i],{i,0,rankAffineg-1}];

simpleAffineRoots=Table[SimpleAffineRoot[i],{i,0,rankAffineg-1}];
\[Delta]={0fundamentalWeights[[1]],0,1};
(* Overscript[\[Rho], ^]=\!\(
\*SubsuperscriptBox[\(\[Sum]\), \(i = 0\), \(r\)]
\*SubscriptBox[
OverscriptBox[\(\[Omega]\), \(^\)], \(i\)]\) *)
\[Rho]hat=Sum[FundamentalAffineWeight[i],{i,0,rankg}];
affineHighestRoot={highestRoot,0,0};
(* scalar product between Affine weights *)
ScalarProduct[\[Mu]_?IsAffineWeight,\[Nu]_?IsAffineWeight]:=ScalarProduct[\[Mu][[1]],\[Nu][[1]]]+\[Mu][[2]]\[Nu][[3]]+\[Mu][[3]]\[Nu][[2]];
];
GetAffineAlgebra[D4]
\[Delta]-(SimpleAffineRoot[0]+{highestRoot,0,0})
hcheck-(1+Sum[coMarks[[i]],{i,rankg}])


(* ::Input::Initialization:: *)
Clear[CoRootBasis]

CoRootBasis[w_]:=Table[ScalarProduct[w,simpleCoRoots[[i]]],{i,rankg}]


(* ::Input::Initialization:: *)
Clear[LongRoots,LengthSquare,SimpleRoots]

LengthSquare[w_,g_:\[ScriptG]]:=ScalarProduct[w,w];
LongRoots[g_:\[ScriptG]]:=Cases[PositiveRoots[g],x_/;LengthSquare[x,x]==2];
SimpleRoots[g_:\[ScriptG]]:=OrthogonalSimpleRoots[g]//OmegaBasis


(* ::Input::Initialization:: *)
Clear[Dynkin]
Dynkin[l__]:=Weight[\[ScriptG]//AlgebraClass][l];


(* ::Input::Initialization:: *)
(* based on [J^a,J^b] = Subscript[\[ImaginaryI]f^ab, c]J^c *)

Clear[simplifyLieAlgebra]
simplifyLieAlgebra[exp_]:=exp//.{
KK[aa_,bb_]KKD[cc_,dd_]:>\[Delta]@@Complement[Union[{aa,bb},{cc,dd}],Intersection[{aa,bb},{cc,dd}]]/;Length[Intersection[{aa,bb},{cc,dd}]]==1,

KK[a_,b_]KKD[c_,d_]:>dimg/;Length[Intersection[{a,b},{c,d}]]==2,

\[Delta][a_,b_]x_:>(x/.{a->b})/;(!TrueQ[D[x,a]==0]),
\[Delta][a_,b_]x_:>(x/.{b->a})/;(!TrueQ[D[x,b]==0]),

\[Delta][a_,a_]:>dimg,
\[Delta][a_,b_]\[Delta][c_,d_]:>dimg/;(Intersection[{a,b},{c,d}]//Length)==2,
\[Delta][a_,b_]^2:>dimg,


(* f[a,b,c][] = f^abc, f[a,b][c] = Subscript[f^ab, c], f[a][b,c] = Subscript[f^a, bc], f[][a,b,c] = Subscript[f, abc] *)

KK[aa_,bb_]f[ii___][jj___]:>KfContraction[KK[aa,bb],f[ii][jj]]/;Length[Intersection[{aa,bb},{jj}]]>=1,
KKD[aa_,bb_]f[ii___][jj___]:>KfContraction[KKD[aa,bb],f[ii][jj]]/;Length[Intersection[{aa,bb},{ii}]]>=1,

(* Subscript[(f^a) , ab] = Subscript[(f^ab) , b] = 0*)
f[a_,b_][c_]:>0/;Length[Intersection[{a,b},{c}]]>0,
f[a_][b_,c_]:>0/;Length[Intersection[{a},{b,c}]]>0,

f[dd_,ee_,ff_][]:>Signature[{dd,ee,ff}](f@@Sort[{dd,ee,ff}])[]/;!TrueQ[{dd,ee,ff}==Sort[{dd,ee,ff}]],
f[][dd_,ee_,ff_]:>Signature[{dd,ee,ff}](f[]@@Sort[{dd,ee,ff}])/;!TrueQ[{dd,ee,ff}==Sort[{dd,ee,ff}]],

(* Subscript[f^ab, c] Subscript[f^d, ab] = 2h^vSubscript[\[Delta], c]^d *)
f[i___][j___]f[k___][l___]:>ffContraction[f[i][j],f[k][l]]/;Length[Intersection[{i}~Join~{j},{k}~Join~{l}]]==2,

(* f^abc Subscript[f, abc] = 2h^v dimg *)
f[i___][j___]f[k___][l___]:>ffContraction[f[i][j],f[k][l]]/;Length[Intersection[{i}~Join~{j},{k}~Join~{l}]]==3,


(* fff relations, Subscript[f^a, bc]Subscript[f^ba^\[Prime], d]Subscript[f^cd, e] = h^vSubscript[f^aa^\[Prime], c] *)
f[i1___][j1___]f[i2___][j2___]f[i3___][j3___]:>fffContraction[f[i1][j1],f[i2][j2],f[i3][j3]]/; Length[Intersection[{i1}~Join~{j1},{i2}~Join~{j2}]]==1&&Length[Intersection[{i3}~Join~{j3},{i2}~Join~{j2}]]==1&&Length[Intersection[{i1}~Join~{j1},{i3}~Join~{j3}]]==1,


f[a_][b_,c_]NNO[J[b_],J[c_]]:>I hcheck Derivative[1][J[a]],
f[a_][b_,c_]NNO[J[c_],J[b_]]:>-I hcheck Derivative[1][J[a]],

f[][d_,e_,f_]NNO[J[a_],NNO[J[b_],J[c_]]]:>Signature[{d,e,f}]Signature[{a,b,c}](I hcheck KKD[cc,dd]NNO[Derivative[1][J[dd]],J[cc]]/.{cc->c[RandomInteger[10000]],dd->d[RandomInteger[10000]]})/;Length[Intersection[{d,e,f},{a,b,c}]]==3

};

Clear[ffContraction]


(* full contraction of ff *)
ffContraction[f[i___][j___],f[k___][l___]]:=Module[{},
Signature[{i}~Join~{j}]Signature[{k}~Join~{l}]2hcheck  dimg
]/;Length[Intersection[{i}~Join~{j},{k}~Join~{l}]]==3;


KfContraction[KK[a_,b_],f[i___][j___]]:=Module[{raised,raisedTo},
raised=Intersection[{a,b},{j}][[1]];
raisedTo=Complement[{a,b},{raised}][[1]];
Signature[{j}]Signature[{raised}~Join~Complement[{j},{raised}]]f[i,raisedTo]@@Complement[{j},{raised}]
];

KfContraction[KKD[a_,b_],f[i___][j___]]:=Module[{lowered,loweredTo},
lowered=Intersection[{a,b},{i}][[1]];
loweredTo=Complement[{a,b},{lowered}][[1]];
Signature[{i}]Signature[Complement[{i},{lowered}]~Join~{lowered}](f@@Complement[{i},{lowered}])@@({loweredTo}~Join~{j})
];


fffContraction[f[i1___][j1___],f[i2___][j2___],f[i3___][j3___]]:=Module[{up1,down1,up2,down2,up3,down3,remain1,remain2,remain3,
inter12,inter13,inter23,up,down
},
up1={i1};
down1={j1};
up2={i2};
down2={j2};
up3={i3};
down3={j3};
inter12=Intersection[{i1}~Join~{j1},{i2}~Join~{j2}];
inter13=Intersection[{i1}~Join~{j1},{i3}~Join~{j3}];
inter23=Intersection[{i2}~Join~{j2},{i3}~Join~{j3}];

remain1=Complement[up1~Join~down1,inter12~Join~inter13];
remain2=Complement[up2~Join~down2,inter12~Join~inter23];
remain3=Complement[up3~Join~down3,inter13~Join~inter23];

up={};
down={};
If[MemberQ[up1,remain1[[1]]],up=up~Join~remain1,down=down~Join~remain1];
If[MemberQ[up2,remain2[[1]]],up=up~Join~remain2,down=down~Join~remain2];
If[MemberQ[up3,remain3[[1]]],up=up~Join~remain3,down=down~Join~remain3];

Signature[up1~Join~down1]Signature[up2~Join~down2]Signature[up3~Join~down3]Signature[inter13~Join~inter12~Join~remain1]Signature[inter23~Join~remain2~Join~inter12]Signature[remain3~Join~inter13~Join~inter23]Signature[up~Join~down]Signature[remain1~Join~remain2~Join~remain3]*(-hcheck)(f@@up)@@down

]/; Length[Intersection[{i1}~Join~{j1},{i2}~Join~{j2}]]==1&&Length[Intersection[{i3}~Join~{j3},{i2}~Join~{j2}]]==1&&Length[Intersection[{i1}~Join~{j1},{i3}~Join~{j3}]]==1


(* partial contraction of ff *)
ffContraction[f[i___][j___],f[k___][l___]]:=Module[{up1,down1,up2,down2,intersection,remain1,remain2,$m},
up1={i};
down1={j};
up2={k};
down2={l};

intersection=Intersection[{i}~Join~{j},{k}~Join~{l}];
remain1=Complement[{i}~Join~{j},intersection][[1]];
remain2=Complement[{k}~Join~{l},intersection][[1]];
If[MemberQ[up1,remain1]&&MemberQ[up2,remain2],$m=KK[remain1,remain2]];
If[MemberQ[down1,remain1]&&MemberQ[down2,remain2],$m=KKD[remain1,remain2]];
If[MemberQ[up1,remain1]&&MemberQ[down2,remain2]||MemberQ[down1,remain1]&&MemberQ[up2,remain2],$m=\[Delta][remain1,remain2]];
2hcheck Signature[{i}~Join~{j}]Signature[{k}~Join~{l}]Signature[intersection~Join~{remain1}]Signature[intersection~Join~{remain2}]$m

]/;Length[Intersection[{i}~Join~{j},{k}~Join~{l}]]==2;


(* ::Input::Initialization:: *)
Clear[IsRoot,IsPositiveRoot,IsSimpleRoot,IsPositiveAffineRoot,IsRealAffineRoot,IsZeroWeight,IsPositiveRealAffineRoot]
(* \:5224\:65ad \[Lambda] \:662f\:5426 finite weight\:ff0c\:770b\:5b83\:7684\:5934\:662f\:5426 Weight \:6216\:8005 RootOmega *)
IsWeight[\[Lambda]_]:=MatchQ[Head[\[Lambda]],Weight[_]]||MatchQ[Head[\[Lambda]],RootOmega[_]]||\[Lambda]==0;
IsZeroWeight[\[Lambda]_]:=(TrueQ[\[Lambda]==ConstantArray[0,rankg]//Simplify])||DynkinLabel[\[Lambda]]==ConstantArray[0,rankg]

(* \:5224\:65ad \[Alpha] \:662f\:5426 finite root\:ff0c\:770b\:5b83\:662f\:5426\:5c5e\:4e8e roots \:96c6\:5408\:ff0c\:6216\:8005\:662f\:5426\:8868\:8fbe\:6210 weight \:7684 roots *)
IsRoot[\[Alpha]_]:=MemberQ[roots,\[Alpha]]||MemberQ[roots/.RootOmega->Weight,\[Alpha]]||MemberQ[rootsSTDBasis,\[Alpha]]
IsPositiveRoot[\[Alpha]_]:=MemberQ[positiveRoots,\[Alpha]]||MemberQ[positiveRoots/.RootOmega->Weight,\[Alpha]]||MemberQ[positiveRootsSTDBasis,\[Alpha]]
IsSimpleRoot[\[Alpha]_]:=MemberQ[simpleRoots,\[Alpha]]||MemberQ[simpleRoots/.RootOmega->Weight,\[Alpha]]||MemberQ[simpleRootsSTDBasis,\[Alpha]]


(* \:5224\:65ad \[Alpha] \:662f\:5426 affine root\:ff0c\:770b\:5b83\:662f\:5426\:4e09\:5206\:91cf\:ff0c\:4e14\:7b2c\:4e00\:5206\:91cf\:662f\:5426\:4e00\:4e2a finite root *)
(* affine root: {\[Alpha],0,n}\:ff0cn\[Element]Z *)
IsAffineRoot[\[Alpha]_]:=MatchQ[\[Alpha],{_,_,_}]&&(IsRoot[\[Alpha][[1]]]||IsZeroWeight[\[Alpha][[1]]]);
(* \:5224\:65ad \[Lambda] \:662f\:5426 affine weight\:ff0c\:770b\:5b83\:662f\:5426\:4e09\:5206\:91cf\:ff0c\:4e14\:7b2c\:4e00\:5206\:91cf\:662f\:5426\:4e00\:4e2a finite weight *)
IsAffineWeight[\[Lambda]_]:=MatchQ[\[Lambda],{_,_,_}]&&IsWeight[\[Lambda][[1]]]

(* \:5224\:65ad \[Alpha]\[Element]Subscript[Overscript[\[CapitalDelta], ^], +]\:ff1a(\[Alpha]\[Element]Subscript[\[CapitalDelta], +],0,n=0) || (\[Alpha]\[Element]\[CapitalDelta],0,n\[GreaterEqual]1) || (\[Alpha]=0,0,n\[GreaterEqual]1)\:ff0c\:5176\:4e2d\:7b2c\:4e09\:79cd\:60c5\:51b5\:662f \:6b63\:865a\:6839 \[Delta] *)
(* \:6ce8\:610f \:5f53 \[Alpha]\[Element]Subscript[\[CapitalDelta], +]\:ff0cn \:4e0d\:80fd\:662f\:8d1f\:6570 *)
IsPositiveAffineRoot[\[Alpha]_]:=False;
IsPositiveAffineRoot[\[Alpha]_?IsAffineRoot]:=(IsPositiveRoot[\[Alpha][[1]]]&&\[Alpha][[3]]==0)||(IsRoot[\[Alpha][[1]]]&&\[Alpha][[3]]>=1)||(IsZeroWeight[\[Alpha][[1]]]&&\[Alpha][[3]]>=1)

(* (0,0,n) \:662f\:865a\:6839\:ff0c\:5373\:7b2c\:4e00\:4e2a\:5206\:91cf\:662f zero weight \:7684\:65f6\:5019\:ff1b\:5176\:5b83\:60c5\:51b5\:79f0\:4e3a\:5b9e\:6839 *)
IsRealAffineRoot[\[Alpha]_]:=False;
IsRealAffineRoot[\[Alpha]_?IsAffineRoot]:=!TrueQ[\[Alpha][[1]]!=0fundamentalWeights[[1]]]

IsPositiveRealAffineRoot[\[Alpha]_]:=False;
(* \!\(
\*SubsuperscriptBox[
OverscriptBox[\(\[CapitalDelta]\), \(^\)], \(+\), \(re\)]\  = \ \(
\*SubscriptBox[\(\[CapitalDelta]\), \(+\)]\ U\ {\[Alpha] + n\[Delta] | \[Alpha] \[Element] \[CapitalDelta], n > 0}\)\) *)
IsPositiveRealAffineRoot[\[Alpha]_?IsAffineRoot]:=IsPositiveAffineRoot[\[Alpha]]&&IsRealAffineRoot[\[Alpha]];



(* ::Input::Initialization:: *)
Clear[GetKillingForm];


ScalarProduct[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]]:=Sum[KDab[[II,JJ]]\[Alpha][[II]]\[Beta][[JJ]],{II,rankg},{JJ,rankg}];
ScalarProduct[\[Alpha]_/;(Head[\[Alpha]]==List)&&Length[\[Alpha]]==rankg,\[Beta]_/;(Head[\[Beta]]==List)&&Length[\[Beta]]==rankg]:=Sum[KDab[[II,JJ]]\[Alpha][[II]]\[Beta][[JJ]],{II,rankg},{JJ,rankg}];


GetKillingForm[Hmatrix_List,EEmatrix_]:=Module[{$\[Lambda]},
(* Hmatrix should be List *)
(* EEmatrix should be functions that turns a root to matrix *)
Print["Getting Killing form"];
Clear[IsMatrix];
Clear[KillingForm,KillingFormD,Kab,KDab,Kij,KDij,
KillingFormD,hChevalley,
KillingFormChevalley,KillingFormDChevalley];

CW=Table[Hmatrix[[II]],{II,rankg}]~Join~Table[EEmatrix[rootsSTDBasis[[i]]],{i,Length[rootsSTDBasis]}];

IsMatrix[X_]:=(Dimensions[X]==Dimensions[CW[[1]]]);


(* K^IJ = 1/(2h^v)Sum[\[Alpha]^I\[Alpha]^J,\[Alpha]] = $\[Lambda]/(2h^v)Subscript[Tr, \[Rho]]H^IH^J, find $\[Lambda] *)
$\[Lambda]=($\[Lambda]/.Solve[
Table[
Sum[rootsSTDBasis[[i]][[II]]*rootsSTDBasis[[i]][[JJ]],{i,Length[rootsSTDBasis]}]-$\[Lambda] Tr[Hmatrix[[II]] . Hmatrix[[JJ]]],{II,rankg},{JJ,rankg}]==0IdentityMatrix[rankg],$\[Lambda]][[1]]);

(* K(X,Y) *)
KillingForm[X_/;IsMatrix[X],Y_/;IsMatrix[Y]]:=$\[Lambda]/(2hcheck) Tr[X . Y];
(* K^IJ *)
KillingForm[II_/;1<=II<=rankg,JJ_/;1<=JJ<=rankg]:=KillingForm[Hmatrix[[II]],Hmatrix[[JJ]]];
(* K^\[Alpha]\[Beta] *)
KillingForm[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]]:=KillingForm[EEmatrix[\[Alpha]],EEmatrix[\[Beta]]];
KillingForm[II_/;1<=II<=rankg,\[Beta]_/;IsRoot[\[Beta]]]:=0;
KillingForm[\[Beta]_/;IsRoot[\[Beta]],II_/;1<=II<=rankg]:=0;


Kab=Table[KillingForm[CW[[a]],CW[[b]]],{a,dimg},{b,dimg}];
(* Subscript[K, ab] *)
KDab=Kab//Inverse;

(* Subscript[K, IJ] *)
KillingFormD[II_/;1<=II<=rankg,JJ_/;1<=JJ<=rankg]:=KDab[[II,JJ]];
(* Subscript[K, \[Alpha],\[Beta]] *)
KillingFormD[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]]:=KDab[[Position[CW,EEmatrix[\[Alpha]]][[1,1]],Position[CW,EEmatrix[\[Beta]]][[1,1]]]];
(* Subscript[K, \[Alpha]i] *)
KillingFormD[II_/;1<=II<=rankg,\[Beta]_/;IsRoot[\[Beta]]]:=0;
KillingFormD[\[Beta]_/;IsRoot[\[Beta]],II_/;1<=II<=rankg]:=0;

hChevalley[i_/;1<=i<=rankg]:=(2Sum[KDab[[II,JJ]]simpleRootsSTDBasis[[i]][[II]]Hmatrix[[JJ]],{II,rankg},{JJ,rankg}])/ScalarProduct[simpleRootsSTDBasis[[i]],simpleRootsSTDBasis[[i]]];
(* K^ij *)
(* In general, K^ij = (\!\(
\*SubsuperscriptBox[\(\[Alpha]\), \(i\), \(v\)], 
\*SubsuperscriptBox[\(\[Alpha]\), \(j\), \(v\)]\)), because h^i = 2 \!\(
\*SubsuperscriptBox[\(\[Alpha]\), \(i\), \(v\)] . H\) *)
Kij=Table[$\[Lambda]/(2hcheck) Tr[hChevalley[i] . hChevalley[j]],{i,rankg},{j,rankg}];

(* K^ij, K^(\[Alpha],-\[Alpha]) *)
KillingFormChevalley[i_/;1<=i<=rankg,j_/;1<=j<=rankg]:=KillingFormChevalley[i,j]=Kij[[i,j]];
KillingFormChevalley[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]]:=KillingFormChevalley[\[Alpha],\[Beta]]=KillingForm[\[Alpha],\[Beta]];
KillingFormChevalley[i_/;1<=i<=rankg,\[Alpha]_/;IsRoot[\[Alpha]]]:=0;
KillingFormChevalley[\[Alpha]_/;IsRoot[\[Alpha]],i_/;1<=i<=rankg]:=0;
(* Subscript[K, ij] *)
KDij=Inverse[Kij];
KillingFormDChevalley[i_/;1<=i<=rankg,j_/;1<=j<=rankg]:=KillingFormDChevalley[i,j]=KDij[[i,j]];
KillingFormDChevalley[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]]:=KillingFormDChevalley[\[Alpha],\[Beta]]=KillingFormD[\[Alpha],\[Beta]];
KillingFormDChevalley[i_/;1<=i<=rankg,\[Alpha]_/;IsRoot[\[Alpha]]]:=KillingFormDChevalley[i,\[Alpha]]=0;
KillingFormDChevalley[\[Alpha]_/;IsRoot[\[Alpha]],i_/;1<=i<=rankg]:=KillingFormDChevalley[\[Alpha],i]=0
];


(* ::Input::Initialization:: *)
(* Translators to and from LieART *)
Clear[DynkinLabel,Heights];
DynkinLabel[w_/;Head[w]==List]:=Table[\[Lambda][i],{i,rankg}]/.Solve[Sum[\[Lambda][i]fundamentalWeightsSTDBasis[[i]],{i,rankg}]-w==ConstantArray[0,rankg],Table[\[Lambda][i],{i,rankg}]][[1]]//FullSimplify;

DynkinLabel[w_/;Head[Head[w]]==RootOmega]:=w/.RootOmega[x_]:>List
DynkinLabel[w_/;Head[Head[w]]==Weight]:=w/.Weight[x_]:>List


Heights[\[Alpha]_/;Head@Head@\[Alpha]==RootOmega]:=\[Alpha]//AlphaBasis;
Heights[\[Alpha]_/;Head@Head@\[Alpha]==Weight]:=\[Alpha]//AlphaBasis;

Heights[\[Alpha]_/;IsRoot[\[Alpha]]]:=Heights[\[Alpha]]=Table[m[i],{i,rankg}]/.Solve[Sum[m[i]simpleRootsSTDBasis[[i]],{i,rankg}]-\[Alpha]==ConstantArray[0,rankg],Table[m[i],{i,rankg}]][[1]]//FullSimplify;


(* ::Input::Initialization:: *)
Clear[ToLieArt,ToSTD]

ToLieArt[w_/;Head[w]==List]:=RootOmega[\[ScriptG]/.Algebra[t_][r_]:>t]@@(w//DynkinLabel);
ToLieArt[w_]:=w;

ToSTD[\[Lambda]_/;Head[Head[\[Lambda]]]==Weight]:=Sum[\[Lambda][[i]]fundamentalWeightsSTDBasis[[i]],{i,rankg}];
ToSTD[\[Lambda]_/;Head[Head[\[Lambda]]]==RootOmega]:=Sum[\[Lambda][[i]]fundamentalWeightsSTDBasis[[i]],{i,rankg}]


(* ::Input::Initialization:: *)
(* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  *)
(* !!! structure constant based on [J^A,J^B] = Subscript[f^AB, C] (J^C) !!! *)
GetStructureConstants[Hmatrix_,EEmatrix_]:=Module[{},
Clear[fabc,fabcChevalley];
fabc[a_,b_][c_]:=0;
(* Subscript[f^I\[Alpha], \[Beta]] = \[Alpha]^ISubsuperscript[\[Delta], \[Beta], \[Alpha]] *)
fabc[II_/;1<=II<=rankg,\[Beta]_/;IsRoot[\[Beta]]][\[Gamma]_]:=\[Beta][[II]]KroneckerDelta[\[Beta],\[Gamma]];
(* Subscript[f^\[Alpha]I, \[Alpha]] = -\[Alpha]^ISubsuperscript[\[Delta], \[Beta], \[Alpha]] *)
fabc[\[Beta]_/;IsRoot[\[Beta]],II_/;1<=II<=rankg][\[Gamma]_]:=-\[Beta][[II]]KroneckerDelta[\[Beta],\[Gamma]];
(* Subscript[(f^(\[Alpha],-\[Alpha])) , I] = K^(\[Alpha],-\[Alpha]) Subscript[K, IJ]\[Alpha]^J *)
fabc[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]][II_/;1<=II<=rankg]:=KillingForm[\[Alpha],-\[Alpha]]Sum[KDab[[II,JJ]]\[Alpha][[JJ]],{JJ,rankg}]/; \[Alpha]+\[Beta]==ConstantArray[0,rankg];

(* Subscript[f^\[Alpha]\[Beta], \[Alpha]+\[Beta]] *)
fabc[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]][\[Gamma]_]:=KillingForm[(EEmatrix[\[Alpha]] . EEmatrix[\[Beta]]-EEmatrix[\[Beta]] . EEmatrix[\[Alpha]]),EEmatrix[-\[Alpha]-\[Beta]//Simplify]]/KillingForm[\[Alpha]+\[Beta]//Simplify,-(\[Alpha]+\[Beta])//Simplify]/;IsRoot[\[Alpha]+\[Beta]//Simplify]&&(\[Alpha]+\[Beta]==\[Gamma]//Simplify);

(* Subscript[f^i\[Alpha], \[Alpha]] = (2(\[Alpha]i,\[Alpha]))/(|\[Alpha](|^2)) = (\!\(
\*SubsuperscriptBox[\(\[Alpha]\), \(i\), \(v\)], \[Alpha]\)) *)

fabcChevalley[a_,b_][c_]:=0;
fabcChevalley[i_/;1<=i<=rankg,\[Alpha]_/;IsRoot[\[Alpha]]][\[Gamma]_/;IsRoot[\[Gamma]]]:= If[TrueQ[\[Alpha]==\[Gamma]],1,0]*(2ScalarProduct[simpleRoots[[i]],\[Alpha]//ToLieArt])/ScalarProduct[simpleRoots[[i]],simpleRoots[[i]]];

(* Subscript[f^\[Alpha]i, \[Alpha]] = -((2(\[Alpha]i,\[Alpha]))/(|Subscript[\[Alpha], i](|^2))) = -(\!\(
\*SubsuperscriptBox[\(\[Alpha]\), \(i\), \(v\)], \[Alpha]\)) *)
fabcChevalley[\[Alpha]_/;IsRoot[\[Alpha]],i_/;1<=i<=rankg][\[Gamma]_/;IsRoot[\[Gamma]]]:=- If[TrueQ[\[Alpha]==\[Gamma]],1,0]*ScalarProduct[2simpleRoots[[i]],\[Alpha]//ToLieArt]/ScalarProduct[simpleRoots[[i]],simpleRoots[[i]]];

(* Subscript[f^(\[Alpha],-\[Alpha]), i] *)
fabcChevalley[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]][i_/;1<=i<=rankg]:=(Heights[\[Alpha]])[[i]]KillingForm[\[Alpha],-\[Alpha]]*ScalarProduct[simpleRootsSTDBasis[[i]],simpleRootsSTDBasis[[i]]]/2/;(TrueQ[\[Alpha]+\[Beta]==ConstantArray[0,rankg]//Simplify]||DynkinLabel[\[Alpha]+\[Beta]]==ConstantArray[0,rankg]);

(* Subscript[f^(\[Alpha],\[Beta]), \[Alpha]+\[Beta]] *)
fabcChevalley[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]][\[Gamma]_]:= KillingForm[(EEmatrix[\[Alpha]] . EEmatrix[\[Beta]]-EEmatrix[\[Beta]] . EEmatrix[\[Alpha]]),EEmatrix[-\[Alpha]-\[Beta]//Simplify]]/KillingForm[\[Alpha]+\[Beta]//Simplify,-(\[Alpha]+\[Beta])//Simplify]/;IsRoot[\[Alpha]+\[Beta]//Simplify]&&(\[Alpha]+\[Beta]==\[Gamma]//Simplify);
fabcChevalley[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]][\[Gamma]_]:=0/;!IsRoot[\[Alpha]+\[Beta]//Simplify]||!TrueQ[\[Alpha]+\[Beta]==\[Gamma]//Simplify];

(* Subscript[f, \[Alpha]\[Beta]i], Subscript[f, ijk], Subscript[f, \[Alpha]\[Beta]\[Gamma]], Subscript[f, ij\[Alpha]] *)
fabcChevalley[][a_,b_,c_]:=Sum[KillingFormDChevalley[a,ap]KillingFormDChevalley[b,bp]fabcChevalley[ap,bp][c],
{ap,Table[i,{i,rankg}]~Join~roots},{bp,Table[i,{i,rankg}]~Join~roots}
];

fabcChevalley[a_,b_,c_][]:=Sum[KillingFormChevalley[c,cp]fabcChevalley[a,b][cp],
{cp,Table[i,{i,rankg}]~Join~roots}
];

];



(* ::Input::Initialization:: *)
Clear[GetMatrices]
GetMatrices[Algebra[A][r_]]:=Module[{Commutator,NN,II,i,j,\[Alpha],$\[Lambda],eqs,\[Alpha]components,sol},
(* initilization *)
(* Hmatrix and EEmatrix will be fed to GetKillingForm *)
Clear[Eij,Hmatrix,EEmatrix];

Print["GetMatrices"];
\[ScriptG]=Algebra[A][r];
rootsSTDBasis={};
simpleRootsSTDBasis={};
positiveRootsSTDBasis={};
simplecoRootsSTDBasis={};
fundamentalWeightsSTDBasis={};
NN=r+1;
Commutator[X_,Y_]:=X . Y-Y . X;


Eij[NN_][i_,j_]:=SparseArray[{{i,j}->1},{NN,NN}];
Hmatrix=Table[0,{II,r}];
(* Construct Cartan generators *)
(* Hmatrix is a List *)
For[II=1,II<=r,II++,
Hmatrix[[II]]=ArrayFlatten[({
 {IdentityMatrix[II], 0},
 {0, 0*IdentityMatrix[NN-II]}
})];
Hmatrix[[II]][[II+1,II+1]]=-II;
Hmatrix[[II]]=1/Sqrt[II+(-II)^2] Hmatrix[[II]];
];

(* Construct ladder matrices w.r.t. positive roots *)
For[i=1,i<=NN,i++,
For[j=i+1,j<=NN,j++,
eqs=Table[Commutator[Hmatrix[[II]],Eij[NN][i,j]]-\[Alpha][II]Eij[NN][i,j]==0,{II,1,r}]//Flatten;
\[Alpha]components=Table[\[Alpha][II],{II,1,r}];
sol=Solve[eqs,\[Alpha]components];
If[j==i+1,
simpleRootsSTDBasis=simpleRootsSTDBasis~Join~{\[Alpha]components/.sol[[1]]}//FullSimplify;
simplecoRootsSTDBasis=simpleRootsSTDBasis~Join~{2/(\[Alpha]components/.sol[[1]]) . (\[Alpha]components/.sol[[1]]) (\[Alpha]components/.sol[[1]])}//FullSimplify
];

EEmatrix[\[Alpha]components/.sol[[1]]]=Eij[NN][i,j]//FullSimplify;
rootsSTDBasis=rootsSTDBasis~Join~{\[Alpha]components/.sol[[1]]}//FullSimplify;
positiveRootsSTDBasis=positiveRootsSTDBasis~Join~{\[Alpha]components/.sol[[1]]}//FullSimplify;

];
];



(* Construct ladder matrices w.r.t. negative roots *)
For[i=1,i<=NN,i++,
For[j=1,j<=i-1,j++,
eqs=Table[Commutator[Hmatrix[[II]],Eij[NN][i,j]]-\[Alpha][II]Eij[NN][i,j]==0,{II,1,r}]//Flatten;
sol=Solve[eqs,Table[\[Alpha][II],{II,1,r}]];
rootsSTDBasis=rootsSTDBasis~Join~{Table[\[Alpha][II],{II,1,r}]/.sol[[1]]};
EEmatrix[\[Alpha]components/.sol[[1]]]=Eij[NN][i,j];
]
];
EEmatrix[\[Alpha]_/;IsRoot[\[Alpha]]]:=EEmatrix[\[Alpha]//ToSTD//Simplify];

(* Up to this point *)
(* Hmatrix, EEmatrix, rootsSTDBasis, simpleRootsSTDBasis, positiveRootsSTDBasis should all be ready *)
(* Construct Killing form *)
GetKillingForm[Hmatrix,EEmatrix];


simplecoRootsSTDBasis=Table[(2simpleRootsSTDBasis[[i]])/ScalarProduct[simpleRootsSTDBasis[[i]],simpleRootsSTDBasis[[i]]],{i,rankg}];

(* fundamental weights *)
fundamentalWeightsSTDBasis=Inverse[CartanMatrix[\[ScriptG]]] . simpleRootsSTDBasis;

GetStructureConstants[Hmatrix,EEmatrix];

Clear[CasimirChevalley,CasimirDChevalley];
CasimirChevalley[3][a_,b_,c_]:=CasimirChevalley[3][a,b,c]=Tr[($J[a] . $J[b]+$J[b] . $J[a]) . $J[c]]/.{$J[i_?IntegerQ]:>hChevalley[i],
$J[\[Alpha]_?IsRoot]:>EEmatrix[\[Alpha]]
};

CasimirDChevalley[3][a_,b_,c_]:=CasimirDChevalley[3][a,b,c]=Table[KillingFormDChevalley[a,ap]KillingFormDChevalley[b,bp]KillingFormDChevalley[c,cp]CasimirChevalley[3][ap,bp,cp],{ap,indices},{bp,indices},{cp,indices}]//Flatten//Total;
];



(* ::Input::Initialization:: *)
GetMatrices[Algebra[B][r_]]:=Module[{\[Delta]\[Delta]},
GetAlgebra[Algebra[B][r]];
\[Delta]\[Delta]=KroneckerDelta;
Hmatrix=Table[ArrayFlatten[({
 {Table[-I(\[Delta]\[Delta][j,2II-1]\[Delta]\[Delta][k,2II]-\[Delta]\[Delta][k,2II-1]\[Delta]\[Delta][j,2II]),{j,2r},{k,2r}], 0},
 {0, 0}
})],{II,rankg}];
Ematrices=Table[ArrayFlatten[({
 {KroneckerProduct[SparseArray[{{II,JJ}->1},r],({
   {1, I \[Eta]p},
   { I \[Eta], -\[Eta] \[Eta]p}
  })], 0},
 {0, 0}
})],
{II,r},{JJ,r},{\[Eta],-1,1,2},{\[Eta]p,-1,1,2}];
Ematrices=Table[Ematrices[[II,JJ,\[Eta],\[Eta]p]]-Transpose[Ematrices[[II,JJ,\[Eta],\[Eta]p]]],
{II,r},{JJ,II+1,r},{\[Eta],-1,1,2},{\[Eta]p,-1,1,2}]//Flatten[#,3]&;

Ematrices=Ematrices~Join~(Table[SparseArray[{{2II-1,2rankg+1}->1,{2rankg+1,2II-1}->-1,{2II,2rankg+1}->I \[Eta],{2rankg+1,2II}->-I \[Eta]}],{II,rankg},{\[Eta],-1,1,2}]//Flatten[#,1]&);

For[\[Alpha]=1,\[Alpha]<=4*(rankg(rankg-1))/2+2rankg,\[Alpha]++,
\[Alpha]\[Alpha]Sol=(Table[Hmatrix[[II]] . Ematrices[[\[Alpha]]]-Ematrices[[\[Alpha]]] . Hmatrix[[II]]-\[Alpha]\[Alpha][II]Ematrices[[\[Alpha]]],{II,rankg}]==0//Solve)[[1]];
EEmatrix[RootOrthogonal[B]@@(({Table[\[Alpha]\[Alpha][II],{II,rankg}]}/.\[Alpha]\[Alpha]Sol)[[1]])//OmegaBasis]=Ematrices[[\[Alpha]]];

EEmatrix[({Table[\[Alpha]\[Alpha][II],{II,rankg}]}/.\[Alpha]\[Alpha]Sol)[[1]]]=Ematrices[[\[Alpha]]];
];

rootsSTDBasis=Table[(roots[[\[Alpha]]]//OrthogonalBasis)/.{RootOrthogonal[B][l__]:>List[l]},{\[Alpha],Length[roots]}];
positiveRootsSTDBasis=Table[(positiveRoots[[\[Alpha]]]//OrthogonalBasis)/.{RootOrthogonal[B][l__]:>List[l]},{\[Alpha],Length[positiveRoots]}];
simpleRootsSTDBasis=Table[(simpleRoots[[\[Alpha]]]//OrthogonalBasis)/.{RootOrthogonal[B][l__]:>List[l]},{\[Alpha],Length[simpleRoots]}];

GetKillingForm[Hmatrix,EEmatrix];

simplecoRootsSTDBasis=Table[(2simpleRootsSTDBasis[[i]])/ScalarProduct[simpleRootsSTDBasis[[i]],simpleRootsSTDBasis[[i]]],{i,rankg}];

(* fundamental weights *)
fundamentalWeightsSTDBasis=Inverse[CartanMatrix[\[ScriptG]]] . simpleRootsSTDBasis;

GetStructureConstants[Hmatrix,EEmatrix]
]/;r!=4




(* ::Input::Initialization:: *)
GetMatrices[D4]:=Module[{Commutator,NN,II,i,j,\[Alpha],$\[Lambda],hD4,ro1,ro2,lo1,lo2,r},
(* initilization *)
(* work out all the H^I, E^\[Alpha] *)
Print["GetMatrices[D4]"];
\[ScriptG]=D4;
r=4;

Commutator[X_,Y_]:=X . Y-Y . X;
Clear[Hmatrix,EEmatrix];

Hmatrix={DiagonalMatrix[{1/2,1/2,0,0,-1/2,-1/2,0,0}],DiagonalMatrix[{1/2,-1/2,0,0,-1/2,1/2,0,0}],DiagonalMatrix[{0,0,1/2,-1/2,0,0,-1/2,1/2}],DiagonalMatrix[{0,0,1/2,1/2,0,0,-1/2,-1/2}]};
ro1=Table[ArrayFlatten[{{Table[KroneckerDelta[k,i]KroneckerDelta[l,j],{k,1,4},{l,1,4}],0},{0,Table[-KroneckerDelta[k,j]KroneckerDelta[l,i],{k,1,4},{l,1,4}]}}],{i,1,3},{j,i+1,4}]//Flatten[#,1]&;
ro2=Table[ArrayFlatten[{{0,Table[KroneckerDelta[k,i]KroneckerDelta[l,j]-KroneckerDelta[k,j]KroneckerDelta[l,i],{k,1,4},{l,1,4}]},{Table[0,{m,1,4},{n,1,4}],0}}],{i,1,3},{j,i+1,4}]//Flatten[#,1]&;
lo1=Table[Transpose[ro1[[i]]],{i,1,6}];
lo2=Table[Transpose[ro2[[i]]],{i,1,6}];
J=Join[Hmatrix,ro1,ro2,lo1,lo2];
JC=Join[Hmatrix,1/2 lo1,1/2 lo2,1/2 ro1,1/2 ro2];
ladderOps=J[[r+1;;]];
ladderOpCs=JC[[r+1;;]];
rootsSTDBasis=Table[Table[Tr[(Hmatrix[[II]] . ladderOps[[\[Alpha]]]-ladderOps[[\[Alpha]]] . Hmatrix[[II]]) . ladderOpCs[[\[Alpha]]]],{II,r}],{\[Alpha],Length[ladderOps]}];
EEmatrix[\[Alpha]_]:=ladderOps[[Position[rootsSTDBasis,\[Alpha]][[1,1]]]];
EEmatrix[\[Alpha]_/;Head[\[Alpha]]==RootOmega[D]]:=EEmatrix[\[Alpha]//ToSTD];

positiveRootsSTDBasis=rootsSTDBasis[[1;;12]];
negativeRootsSTDBasis=rootsSTDBasis[[13;;24]];

simpleRootsSTDBasis={{0,1,0,0},{1/2,-1/2,-1/2,-1/2},{0,0,1,0},{0,0,0,1}};

(* Up to this point *)
(* Hmatrix, EEmatrix, rootsSTDBasis, simpleRootsSTDBasis, positiveRootsSTDBasis should all be ready *)
(* Construct Killing form *)
GetKillingForm[Hmatrix,EEmatrix];

(* fundamental weights *)
fundamentalWeightsSTDBasis=Inverse[CartanMatrix[\[ScriptG]]] . simpleRootsSTDBasis;
simplecoRootsSTDBasis=Table[(2simpleRootsSTDBasis[[i]])/ScalarProduct[simpleRootsSTDBasis[[i]],simpleRootsSTDBasis[[i]]],{i,rankg}];

GetStructureConstants[Hmatrix,EEmatrix]
];



(* ::Input::Initialization:: *)
GetMatrices[Algebra[D][r_]]:=Module[{\[Delta]\[Delta]},
GetAlgebra[Algebra[D][r]];
\[Delta]\[Delta]=KroneckerDelta;
Hmatrix=Table[Table[-I(\[Delta]\[Delta][j,2II-1]\[Delta]\[Delta][k,2II]-\[Delta]\[Delta][k,2II-1]\[Delta]\[Delta][j,2II]),{j,2r},{k,2r}],{II,rankg}];
Ematrices=Table[1/2 KroneckerProduct[SparseArray[{{II,JJ}->1},r],({
 {1, I \[Eta]p},
 { I \[Eta], -\[Eta] \[Eta]p}
})],
{II,r},{JJ,r},{\[Eta],-1,1,2},{\[Eta]p,-1,1,2}];
Ematrices=Table[Ematrices[[II,JJ,\[Eta],\[Eta]p]]-Transpose[Ematrices[[II,JJ,\[Eta],\[Eta]p]]],
{II,r},{JJ,II+1,r},{\[Eta],-1,1,2},{\[Eta]p,-1,1,2}]//Flatten[#,3]&;

For[\[Alpha]=1,\[Alpha]<=4*(rankg(rankg-1))/2,\[Alpha]++,
\[Alpha]\[Alpha]Sol=(Table[Hmatrix[[II]] . Ematrices[[\[Alpha]]]-Ematrices[[\[Alpha]]] . Hmatrix[[II]]-\[Alpha]\[Alpha][II]Ematrices[[\[Alpha]]],{II,rankg}]==0//Solve)[[1]];
EEmatrix[RootOrthogonal[D]@@(({Table[\[Alpha]\[Alpha][II],{II,rankg}]}/.\[Alpha]\[Alpha]Sol)[[1]])//OmegaBasis]=Ematrices[[\[Alpha]]];

EEmatrix[({Table[\[Alpha]\[Alpha][II],{II,rankg}]}/.\[Alpha]\[Alpha]Sol)[[1]]]=Ematrices[[\[Alpha]]];
];

rootsSTDBasis=Table[(roots[[\[Alpha]]]//OrthogonalBasis)/.{RootOrthogonal[D][l__]:>List[l]},{\[Alpha],Length[roots]}];
positiveRootsSTDBasis=Table[(positiveRoots[[\[Alpha]]]//OrthogonalBasis)/.{RootOrthogonal[D][l__]:>List[l]},{\[Alpha],Length[positiveRoots]}];
simpleRootsSTDBasis=Table[(simpleRoots[[\[Alpha]]]//OrthogonalBasis)/.{RootOrthogonal[D][l__]:>List[l]},{\[Alpha],Length[simpleRoots]}];

GetKillingForm[Hmatrix,EEmatrix];

simplecoRootsSTDBasis=Table[(2simpleRootsSTDBasis[[i]])/ScalarProduct[simpleRootsSTDBasis[[i]],simpleRootsSTDBasis[[i]]],{i,rankg}];

(* fundamental weights *)
fundamentalWeightsSTDBasis=Inverse[CartanMatrix[\[ScriptG]]] . simpleRootsSTDBasis;

GetStructureConstants[Hmatrix,EEmatrix]
]/;r!=4




(* ::Input::Initialization:: *)
GetMatrices[G2]:=Module[{Commutator,NN,II,i,j,\[Alpha],$\[Lambda],$$\[Lambda],hD4,ro1,ro2,lo1,lo2,a,b,\[Lambda],r,J,JJx,JJy,sols,Esols},
(* initilization *)
(* work out all the H^I, E^\[Alpha] *)
\[ScriptG]=G2;
GetAlgebra[\[ScriptG]];
r=rankg;
Commutator[X_,Y_]:=X . Y-Y . X;
Clear[Hmatrix];
J=({
 {0, x[3], -x[2], x[5], -x[4], -x[7], -x[6]+y[6]},
 {-x[3], 0, x[1], x[6], -x[7]+y[7], x[4]-y[4], x[5]+y[5]},
 {x[2], -x[1], 0, -y[7], y[6], y[5], y[4]},
 {-x[5], -x[6], y[7], 0, -x[1]+y[1], -x[2]+y[2], -x[3]+y[3]},
 {x[4], x[7]-y[7], -y[6], x[1]-y[1], 0, y[3], -y[2]},
 {x[7], -x[4]+y[4], -y[5], x[2]-y[2], -y[3], 0, y[1]},
 {x[6]-y[6], -x[5]-y[5], -y[4], x[3]-y[3], y[2], -y[1], 0}
});
JJx[a_]:=Coefficient[J,x[a]];
JJy[a_]:=Coefficient[J,y[a]];

Clear[sols];

Hmatrix={I JJx[1],I JJy[1]};
(* find ladder operators with respect to the chosen H^I *)
sols=Solve[{
Commutator[Hmatrix[[1]],Sum[a[i]JJx[i]+b[i]JJy[i],{i,7}]]==\[Lambda][1] (Sum[a[i]JJx[i]+b[i]JJy[i],{i,7}]),
Commutator[Hmatrix[[2]],Sum[a[i]JJx[i]+b[i]JJy[i],{i,7}]]==\[Lambda][2] (Sum[a[i]JJx[i]+b[i]JJy[i],{i,7}])},Table[a[i],{i,7}]~Join~Table[b[i],{i,7}]~Join~{\[Lambda][1],\[Lambda][2]}];
Esols=Table[(Sum[a[i]JJx[i]+b[i]JJy[i],{i,7}]/.sols[[k]]),{k,Length[sols]}];
Ematrices=Join@@Table[(Table[Esols[[s]]//SeriesCoefficient[#,{a[i],0,1}]&,{i,7}])~Join~(Table[Esols[[s]]//SeriesCoefficient[#,{b[i],0,1}]&,{i,7}])//DeleteCases[#,0IdentityMatrix[7]]&,{s,Length[Esols]}];
rootsSTDBasis={};

(* Define EEmatrix *)
For[i=1,i<15,i++,

rootSol=Solve[{Commutator[Hmatrix[[1]],Ematrices[[i]]]-\[Alpha][1]Ematrices[[i]]==0IdentityMatrix[7],
Commutator[Hmatrix[[2]],Ematrices[[i]]]-\[Alpha][2]Ematrices[[i]]==0IdentityMatrix[7]
}];

If[({\[Alpha][1],\[Alpha][2]}/.rootSol[[1]])!={0,0},
rootsSTDBasis=rootsSTDBasis~Join~({{\[Alpha][1],\[Alpha][2]}/.rootSol[[1]]});
EEmatrix[{\[Alpha][1],\[Alpha][2]}/.rootSol[[1]]//Simplify]=Ematrices[[i]]
]
];
EEmatrix[\[Alpha]_/;Head[\[Alpha]]==RootOmega[\[ScriptG]]]:=EEmatrix[\[Alpha]//ToSTD];
positiveRootsSTDBasis=Select[rootsSTDBasis,(#[[1]]>0)||(#[[1]]==0&&#[[2]]>0)&];
negativeRootsSTDBasis=Select[rootsSTDBasis,(#[[1]]<0)||(#[[1]]==0&&#[[2]]<0)&];
simpleRootsSTDBasis={positiveRootsSTDBasis[[5]],positiveRootsSTDBasis[[1]]};

(* Up to this point *)
(* Hmatrix, EEmatrix, rootsSTDBasis, simpleRootsSTDBasis, positiveRootsSTDBasis should all be ready *)
(* Construct Killing form *)
GetKillingForm[Hmatrix,EEmatrix];

(* fundamental weights *)
fundamentalWeightsSTDBasis=Inverse[CartanMatrix[\[ScriptG]]] . simpleRootsSTDBasis;
simplecoRootsSTDBasis=Table[(2simpleRootsSTDBasis[[i]])/ScalarProduct[simpleRootsSTDBasis[[i]],simpleRootsSTDBasis[[i]]],{i,rankg}];

GetStructureConstants[Hmatrix,EEmatrix]
];


(* ::Input::Initialization:: *)
GetMatrices[F4]:=Module[{NN,II,i,j,\[Alpha],$\[Lambda],$$\[Lambda],hD4,ro1,ro2,lo1,lo2,a,b,\[Lambda],r,Timer},
(* initilization *)
(* work out all the H^I, E^\[Alpha] *)


\[ScriptG]=F4;
GetAlgebra[\[ScriptG]];
r=rankg;
Commutator[X_,Y_]:=X . Y-Y . X;

SetDirectory[NotebookDirectory[]];
F4EMatrices=Import["F4EMatrices.txt"]//ToExpression//SparseArray;
F4e=Import["F4e.txt"]//ToExpression//SparseArray;

(* The simple roots are ordered differently between LieART and SageMath *)
(*E7e={E7e\[LeftDoubleBracket]1\[RightDoubleBracket]}~Join~E7e\[LeftDoubleBracket]3;;7\[RightDoubleBracket]~Join~{E7e\[LeftDoubleBracket]2\[RightDoubleBracket]};*)
Hmatrix=Import["F4H.txt"]//ToExpression//SparseArray;

Ematrices=F4EMatrices;


rootsSTDBasis={};


For[i=1,i<=Length[Ematrices],i++,
rootSol=Solve[
Table[Commutator[Hmatrix[[II]],Ematrices[[i]]]-\[Alpha][II]Ematrices[[i]]==0Hmatrix[[II]],{II,rankg}]//Normal
];

If[(Table[\[Alpha][II],{II,rankg}]/.rootSol[[1]])!={0,0},
rootsSTDBasis=rootsSTDBasis~Join~({Table[\[Alpha][II],{II,rankg}]/.rootSol[[1]]});
EEmatrix[Table[\[Alpha][II],{II,rankg}]/.rootSol[[1]]//Simplify]=Ematrices[[i]]
];
];
EEmatrix[\[Alpha]_/;IsRoot[\[Alpha]]]:=EEmatrix[\[Alpha]//ToSTD];

positiveRootsSTDBasis=Select[rootsSTDBasis,(#[[1]]>0)||(#[[1]]==0&&#[[2]]>0)&];
negativeRootsSTDBasis=Select[rootsSTDBasis,(#[[1]]<0)||(#[[1]]==0&&#[[2]]<0)&];

simpleRootsSTDBasis=Table[Table[\[Alpha][i],{i,rankg}]/.(Table[Commutator[Hmatrix[[II]],F4e[[i]]]-\[Alpha][II]F4e[[i]]==0Hmatrix[[II]]//Normal,{II,rankg}]//Solve)[[1]],{i,rankg}];

(* Up to this point *)
(* Hmatrix, EEmatrix, rootsSTDBasis, simpleRootsSTDBasis, positiveRootsSTDBasis should all be ready *)
(* Construct Killing form *)
GetKillingForm[Hmatrix,EEmatrix];

(* fundamental weights *)
fundamentalWeightsSTDBasis=Inverse[CartanMatrix[\[ScriptG]]] . simpleRootsSTDBasis;
simplecoRootsSTDBasis=Table[(2simpleRootsSTDBasis[[i]])/ScalarProduct[simpleRootsSTDBasis[[i]],simpleRootsSTDBasis[[i]]],{i,rankg}];

GetStructureConstants[Hmatrix,EEmatrix];
];


(* ::Input::Initialization:: *)
GetMatrices[E6]:=Module[{Commutator,NN,II,i,j,\[Alpha],$\[Lambda],$$\[Lambda],hD4,ro1,ro2,lo1,lo2,a,b,\[Lambda],
GetAlphaiSequences,GetEMatrices,$counter,$E,r
},
(* initilization *)
Clear[IsMatrix];
IsMatrix[X_]:=(Dimensions[X]==Dimensions[hChevalley[1]]);

\[ScriptG]=E6;
GetAlgebra[\[ScriptG]];
r=rankg;
Commutator[X_,Y_]:=X . Y-Y . X;
SetDirectory[NotebookDirectory[]];

(* the h^i and E^Subscript[\[Alpha], i], E^-Subscript[\[Alpha], i] are from the GroupMath package *)
<<E6e.mx;
<<E6f.mx;
<<E6h.mx;
Clear[hChevalley];
hChevalley[i_]:=E6h[[i]];

Clear[EEmatrix];
For[i=1,i<rankg+1,i++,
EEmatrix[simpleRoots[[i]]]=E6e[[i]];
EEmatrix[-simpleRoots[[i]]]=E6f[[i]];
];

(* Construct E^\[Alpha] based on \[Alpha] = Sum[m[i]Subscript[\[Alpha], i],i] by trying a lot of different ordering  *)
(* [...,[E^Subscript[\[Alpha], k],[E^Subscript[\[Alpha], i],E^Subscript[\[Alpha], j]]]]  *)
Clear[GetAlphaiSequences,GetEMatrices];
GetAlphaiSequences[m_/;m!=ConstantArray[0,6]&&AllTrue[m,#>=0&]]:=Module[{},
(Table[ConstantArray[i,m[[i]]],{i,rankg}]//Flatten//DeleteDuplicates)~Join~(GetAlphaiSequences[Map[Function[x,If[x>0,x-1,x]],m]]//RandomSample)
];

GetAlphaiSequences[m_/;m!=ConstantArray[0,6]&&AllTrue[m,#<=0&]]:=Module[{},
(Table[ConstantArray[-i,-m[[i]]],{i,rankg}]//Flatten//DeleteDuplicates)~Join~(GetAlphaiSequences[Map[Function[x,If[x<0,x+1,x]],m]]//RandomSample)
];

GetAlphaiSequences[\[Alpha]_/;\[Alpha]==ConstantArray[0,6]]:={};

GetEMatrices[m_/;m!=ConstantArray[0,6]&&AllTrue[m,#>=0&]]:=Module[{EList,is},
is=GetAlphaiSequences[m];
EList=Table[E6e[[is[[j]]]],{j,Length[is]}];
Fold[Commutator,EList[[1]],EList[[2;;-1]]]
];

GetEMatrices[m_/;m!=ConstantArray[0,6]&&AllTrue[m,#<=0&]]:=Module[{EList,is},
is=GetAlphaiSequences[m];
EList=Table[E6f[[-is[[j]]]],{j,Length[is]}];
Fold[Commutator,EList[[1]],EList[[2;;-1]]]
];


For[i=1,i<dimg-rankg+1,i++,

$counter=0;

While[!TrueQ[Head[EEmatrix[roots[[i]]]]==SparseArray]&&$counter<100,
$E=GetEMatrices[(roots//AlphaBasis)[[i]]/.{RootAlpha[E6][x___]:>List[x]}];


If[TrueQ[Head[$E]==SparseArray]&&($E//Normal//Simplify)!=ConstantArray[0,{dimg,dimg}],
EEmatrix[roots[[i]]]=$E;
];
$counter=$counter+1;
];
];
EEmatrix[\[Alpha]_/;IsRoot[\[Alpha]]]:=EEmatrix[\[Alpha]//ToSTD];

Clear[Kij,KDij];
(* K^ij = (\!\(
\*SubsuperscriptBox[\(\[Alpha]\), \(i\), \(v\)], 
\*SubsuperscriptBox[\(\[Alpha]\), \(j\), \(v\)]\))) *)
Kij=Table[ScalarProduct[simpleCoRoots[[i]],simpleCoRoots[[j]]],{i,rankg},{j,rankg}];
KDij=Inverse[Kij];

(* $\[Lambda]=1; *)
Clear[KillingForm,KillingFormD];
KillingForm[X_/;IsMatrix[X],Y_/;IsMatrix[Y]]:=1/(2hcheck) Tr[X . Y];
KillingForm[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]]:=1/(2hcheck) Tr[EEmatrix[\[Alpha]] . EEmatrix[\[Beta]]]//Simplify;

KillingFormD[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]]:=1/KillingForm[\[Alpha],\[Beta]]/;((\[Alpha]+\[Beta]==ConstantArray[0,rankg]//Simplify)||(\[Alpha]+\[Beta]/.RootOmega[E6]->List)==ConstantArray[0,rankg]);
KillingFormD[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]]:=0;


Clear[fabcChevalley];
(* Subscript[f^(\[Alpha],-\[Alpha]), i] = Subscript[m, i]K^(\[Alpha],-\[Alpha])*1/2|Subscript[\[Alpha], j]|^2 *)
fabcChevalley[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]][i_/;1<=i<=rankg]:=((\[Alpha]//AlphaBasis)[[i]] KillingForm[\[Alpha],-\[Alpha]]/2 ScalarProduct[simpleRoots[[i]],simpleRoots[[i]]])/;(\[Alpha]+\[Beta]==ConstantArray[0,rankg]//Simplify)||(\[Alpha]+\[Beta]/.RootOmega[E6]->List)==ConstantArray[0,rankg];

(* Subscript[f^\[Alpha]\[Beta], -\[Alpha]-\[Beta]] = (K([E^\[Alpha],E^\[Beta]],E^(-\[Alpha]-\[Beta])))/K^(\[Alpha]+\[Beta],-\[Alpha]-\[Beta]) *)
fabcChevalley[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]][\[Gamma]_]:=KillingForm[(EEmatrix[\[Alpha]] . EEmatrix[\[Beta]]-EEmatrix[\[Beta]] . EEmatrix[\[Alpha]]),EEmatrix[-\[Alpha]-\[Beta]//Simplify]]/KillingForm[\[Alpha]+\[Beta]//Simplify,-(\[Alpha]+\[Beta])//Simplify]/;IsRoot[\[Alpha]+\[Beta]//Simplify]&&(\[Alpha]+\[Beta]==\[Gamma]//Simplify);

(* Subscript[f^\[Alpha]\[Beta], \[Gamma]] = 0 when \[Gamma]\[NotEqual]\[Alpha]+\[Beta] *)
fabcChevalley[\[Alpha]_/;IsRoot[\[Alpha]],\[Beta]_/;IsRoot[\[Beta]]][\[Gamma]_]:=0/;!IsRoot[\[Alpha]+\[Beta]//Simplify]||(\[Alpha]+\[Beta]!=\[Gamma]//Simplify);

];


(* ::Input::Initialization:: *)
GetMatrices[E7]:=Module[{NN,II,i,j,\[Alpha],$\[Lambda],$$\[Lambda],hD4,ro1,ro2,lo1,lo2,a,b,\[Lambda],r,Timer},
(* initilization *)
(* work out all the H^I, E^\[Alpha] *)


\[ScriptG]=E7;
GetAlgebra[\[ScriptG]];
r=rankg;
Commutator[X_,Y_]:=X . Y-Y . X;

SetDirectory[NotebookDirectory[]];
E7Matrices=Import["E7Matrices.txt"]//ToExpression//SparseArray;
E7e=Import["E7e.txt"]//ToExpression//SparseArray;
(* The simple roots are ordered differently between LieART and SageMath *)
E7e={E7e[[1]]}~Join~E7e[[3;;7]]~Join~{E7e[[2]]};
Hmatrix=E7Matrices[[1;;rankg]];

Ematrices=E7Matrices[[rankg+1;;dimg]];


rootsSTDBasis={};


For[i=1,i<=Length[Ematrices],i++,
rootSol=Solve[
Table[Commutator[Hmatrix[[II]],Ematrices[[i]]]-\[Alpha][II]Ematrices[[i]]==0Hmatrix[[II]],{II,rankg}]//Normal
];
If[(Table[\[Alpha][II],{II,rankg}]/.rootSol[[1]])!={0,0},
rootsSTDBasis=rootsSTDBasis~Join~({Table[\[Alpha][II],{II,rankg}]/.rootSol[[1]]});
EEmatrix[Table[\[Alpha][II],{II,rankg}]/.rootSol[[1]]//Simplify]=Ematrices[[i]]
]
];
EEmatrix[\[Alpha]_/;IsRoot[\[Alpha]]]:=EEmatrix[\[Alpha]//ToSTD];

positiveRootsSTDBasis=Select[rootsSTDBasis,(#[[1]]>0)||(#[[1]]==0&&#[[2]]>0)&];
negativeRootsSTDBasis=Select[rootsSTDBasis,(#[[1]]<0)||(#[[1]]==0&&#[[2]]<0)&];
simpleRootsSTDBasis=Table[Table[\[Alpha][i],{i,rankg}]/.(Table[Commutator[Hmatrix[[II]],E7e[[i]]]-\[Alpha][II]E7e[[i]]==0Hmatrix[[II]]//Normal,{II,rankg}]//Solve)[[1]],{i,rankg}];

(* Up to this point *)
(* Hmatrix, EEmatrix, rootsSTDBasis, simpleRootsSTDBasis, positiveRootsSTDBasis should all be ready *)
(* Construct Killing form *)

Hmatrix=Table[Hmatrix[[i]],{i,rankg}];
GetKillingForm[Hmatrix,EEmatrix];

(* fundamental weights *)
fundamentalWeightsSTDBasis=Inverse[CartanMatrix[\[ScriptG]]] . simpleRootsSTDBasis;
simplecoRootsSTDBasis=Table[(2simpleRootsSTDBasis[[i]])/ScalarProduct[simpleRootsSTDBasis[[i]],simpleRootsSTDBasis[[i]]],{i,rankg}];

GetStructureConstants[Hmatrix,EEmatrix];
]


(* ::Input::Initialization:: *)
Clear[Weyl,WeylDot,ss];
Weyl[i_Integer][weight_]:=Reflect[weight,{simpleRoots[[i]]}][[1]];
WeylDot[i_Integer][weight_]:=Weyl[i][weight+WeylVector]-WeylVector;
WeylShifted[i_Integer][w_]:=WeylDot
Weyl[\[Alpha]_?(MatchQ[#,RootOmega[_][___]]&)][weight_]:=weight-ScalarProduct[weight,(2\[Alpha])/ScalarProduct[\[Alpha],\[Alpha]]]\[Alpha]

ss[i_][weight_]:=Weyl[simpleRoots[[i]]][weight]


(* ::Input::Initialization:: *)



(* ::Input::Initialization:: *)
Clear[WeylAffine]

WeylAffine[\[Alpha]_?IsAffineWeight][weight_?IsAffineWeight]:=weight-ScalarProduct[weight,(2\[Alpha])/ScalarProduct[\[Alpha],\[Alpha]]]\[Alpha];
WeylAffine[\[Alpha]_?IsWeight][weight_?IsWeight]:={weight,0,0}-ScalarProduct[weight,(2\[Alpha])/ScalarProduct[\[Alpha],\[Alpha]]]{\[Alpha],0,0}

WeylAffine[\[Alpha]_?IsWeight][weight_?IsAffineWeight]:=weight-ScalarProduct[weight[[1]],(2\[Alpha])/ScalarProduct[\[Alpha],\[Alpha]]]{\[Alpha],0,0};
WeylAffine[\[Alpha]_?IsAffineWeight][weight_?IsWeight]:={weight,0,0}-ScalarProduct[weight,(2\[Alpha][[1]])/ScalarProduct[\[Alpha][[1]],\[Alpha][[1]]]]\[Alpha]



(* \:5bf9\:4e8e \[Alpha]^v \[Element] Q^v *)
(* Subscript[t, \[Alpha]^v]Overscript[\[Lambda], ^] = (\[Lambda]+k\[Alpha]^v; k; n + (|\[Lambda](|^2)-|\[Lambda]+k\[Alpha]^v(|^2))/(2k)) = (\[Lambda]+k\[Alpha]^v; k; n + (- 2(\[Lambda],\[Alpha]^v) - k|\[Alpha]^v|^2)/2) *)
(* \:66f4\:4e00\:822c\:5730\:ff0c\:5bf9\:4e8e \[Beta]\[Element]P^v *)
(* Subscript[t, \[Beta]]Overscript[\[Lambda], ^] = Overscript[\[Lambda], ^]+k\[Beta] - ((\[Lambda],\[Beta])+1/2k (\[Beta],\[Beta]))\[Delta] = {\[Lambda]+k\[Beta],k,n-[(\[Lambda],\[Beta])+k/2(\[Beta],\[Beta])]} *)
Translation[\[Alpha]check_?IsAffineWeight][weight_?IsAffineWeight]:=With[{\[Lambda]=weight[[1]],k=weight[[2]],n=weight[[3]]},
{\[Lambda]+k \[Alpha]check[[1]],
k,
n+(-ScalarProduct[\[Lambda],\[Alpha]check[[1]]]-k/2 ScalarProduct[\[Alpha]check[[1]],\[Alpha]check[[1]]])}
];
Translation[\[Alpha]check_?IsWeight][weight_?IsAffineWeight]:=Translation[{\[Alpha]check,0,0}][weight]


(* ::Input::Initialization:: *)
(*CCOfWeight[\[Lambda]_]:=Module[{iii,\[Lambda]temp},
\[Lambda]temp=\[Lambda];
For[iii=1,iii\[LessEqual]rankg,iii++,
\[Lambda]temp=Weyl[iii][\[Lambda]temp];
];
-\[Lambda]temp
];
*)


(* ::Input::Initialization:: *)
WeylGroupAr[g_:\[ScriptG]]:=Module[
{permMatrix,WeylByPermutation,perms,tempfn,SignatureOfWeyl},
If[((g//Head)==Algebra[A])//TrueQ,True,Print["Not of type A"];Return[]];

permMatrix[perm_]:=Module[{temp},
temp=0IdentityMatrix[Length[perm]];
For[i=1,i<=Length[perm],i++,
temp[[i,perm[[i]]]]=1;
];
temp
];

WeylByPermutation[perm_][w_]:=Module[{wList},
wList=Table[(w//OrthogonalBasis)[[j]],{j,Length[perm]}];
WeightOrthogonal[A]@@(permMatrix[perm] . wList)
];

perms=Permutations[Table[i,{i,1,Rank[g]+1}]];

tempfn[i_]:=(WeylByPermutation[perms[[i]]][#]//OmegaBasis)&;
SignatureOfWeyl[i_]:=Det[permMatrix[perms[[i]]]];

Table[{tempfn[i],SignatureOfWeyl[i]},{i,Factorial[Rank[g]+1]}]

]


(* ::Input::Initialization:: *)
Irrep[a_/;(a//Head//Head)==Algebra][label__]:=If[Length[List[label]]==Rank[a],Irrep[a//AlgebraClass][label],Text["Algebra rank != Dynkin label length"]];


(* Irrep[A3][1,1,1] *)
Irrep[a_/;(a//Head//Head)==Algebra][label__]:=If[Length[List[label]]==Rank[a],Irrep[a//AlgebraClass][label],Text["Algebra rank != Dynkin label length"]];

(* Irrep[A3][{1,1,1}] *)
Irrep[a_/;(a//Head//Head)==Algebra][label_/;Head[label]==List]:=If[
Length[label]==Rank[a],
Irrep[a//AlgebraClass]@@label,
Text["Algebra rank != Dynkin label length"]];

(* Irrep[A3][RootOmega[A][1,1,1] or Weight[A][1,1,1]] *)
Irrep[a_/;(a//Head//Head)==Algebra][label_/;MemberQ[{RootOmega,Weight},Head[Head[label]]]]:=Module[{DynkinLabelList},
DynkinLabelList=Table[label[[i]],{i,rankg}];
Irrep[a][DynkinLabelList]
];

(* Irrep[E678/F4/G2][RootOmega[A][1,1,1] or Weight[A][1,1,1]] *)
Irrep[a_/;MemberQ[{E6,E7,E8,G2,F4},a]][label_/;MemberQ[{RootOmega,Weight},Head[Head[label]]]]:=Module[{DynkinLabelList},

DynkinLabelList=Table[label[[i]],{i,rankg}];
If[Length[DynkinLabelList]==Rank[a],
Irrep[a]@@DynkinLabelList,
Text["Algebra rank != Dynkin label length"]]

];


(* ::Input::Initialization:: *)
Dimq[\[Lambda]_][q_]:=Product[(q^(ScalarProduct[\[Lambda]+WeylVector,positiveRoots[[i]]]/2)-q^(-(ScalarProduct[\[Lambda]+WeylVector,positiveRoots[[i]]]/2)))/(q^(ScalarProduct[WeylVector,positiveRoots[[i]]]/2)-q^(-(ScalarProduct[WeylVector,positiveRoots[[i]]]/2))),{i,Length[positiveRoots]}]


(* ::Input::Initialization:: *)
Clear[CoRootLattice,RootLattice]

RootLattice[g_:g,order_:order]:=Module[{DynamicLattice,rankg,range,simpleRoots},
rankg=Rank[g];
range=Table[{m[i],-order,order},{i,1,rankg}];
DynamicLattice[summand_][range__]:=Table[summand,range];
simpleRoots=OrthogonalSimpleRoots[g]//OmegaBasis;
DynamicLattice[Sum[m[i]coRoots[[i]],{i,rankg}]]@@range
]

CoRootLattice[g_:g,order_:order]:=Module[{DynamicLattice,rankg,range,coRoots},
rankg=Rank[g];
range=Table[{m[i],-order,order},{i,1,rankg}];
DynamicLattice[summand_][range__]:=Table[summand,range];
coRoots=OrthogonalSimpleCoRoots[g]//OmegaBasis;
DynamicLattice[Sum[m[i]coRoots[[i]],{i,rankg}]]@@range
]

