(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetDirectory[NotebookDirectory[]];
SetOptions[InputNotebook[],AutoGeneratedPackage->Automatic]
Import["OPEdefs.m"]



(* ::Input::Initialization:: *)
Clear[IsFundField,IsExpField,IsFreeField]

(* Determine if a field is a fundamental field or linear combination of *)
(* fundamental field *)
(* \[CurlyPhi][z]-->True, \[Delta][z]-->True, (\[CurlyPhi]^\[Prime])[z]-->True, *)
(* (\[ExponentialE]^\[CurlyPhi])[z]-->False, k-->False, (1/(z-w))-->False *)
(* g[z]\[CurlyPhi][z]+f[z]\[Delta][z]-->True, g[z](\[CurlyPhi][z]+f[z]\[Delta][z])-->True *)

IsFundField[f_]:=Module[{pattern},
pattern=Table[{
fieldNames[[i]][z_]:>True,
\!\(\*SuperscriptBox[\(fieldNames\[LeftDoubleBracket]i\[RightDoubleBracket]\), 
TagBox[
RowBox[{"(", "n_", ")"}],
Derivative],
MultilineFunction->None]\)[z_]:>True,
\[Lambda]_ fieldNames[[i]][z_]:>True,
\[Lambda]_ \!\(\*SuperscriptBox[\(fieldNames\[LeftDoubleBracket]i\[RightDoubleBracket]\), 
TagBox[
RowBox[{"(", "n_", ")"}],
Derivative],
MultilineFunction->None]\)[z_]:>True,
a_. e1_[z_]+e2_:>(IsFundField[e1[z]]||IsFundField[a])&&IsFundField[e2]
},
{i,Length[fieldNames]}]//Flatten;

(f//Expand)/.pattern//TrueQ
];


(* ::Input::Initialization:: *)
(* Determine if a simple field is a exponential field *)
(* (\[ExponentialE]^\[CurlyPhi])[z]-->True, (\[ExponentialE]^(\[Lambda] \[CurlyPhi]+\[Mu] \[Delta]))[z]-->True *)
(* \[CurlyPhi][z]-->False, (\[CurlyPhi]^\[Prime])[z]-->False, *)
(* k-->False, (1/(z-w))-->False *)
(* !!! (\[ExponentialE]^(Log[u-v]\[CurlyPhi]))[z] breaks !!! *)
IsExpField[f_]:=Module[{GetPattern,x,ExpressionToFieldFunctionTemp},
ExpressionToFieldFunctionTemp[exp_][z_]:=exp/.{ff_:>ff[z]/;IsFundField[ff[z]]};
(f/.{(E^exp_)[z_]:>E^exp}//ExpressionToFieldFunctionTemp[#][x]&)/.{E^field_:>IsFundField[field]}//TrueQ
];

IsFreeField[f_]:=IsFundField[f]||IsExpField[f];


(* ::Input::Initialization:: *)
(* ======\[Equal] Unittests ======\[Equal] *)
fieldNames={\[CurlyPhi],\[Delta]};

(* IsFundField *)
AllTrue[{\[CurlyPhi][z],Derivative[1][\[CurlyPhi]][z],p \[CurlyPhi][z],\[CurlyPhi][z]+\[Delta][z],p \[CurlyPhi][z]+q \[CurlyPhi][w],p (\[CurlyPhi][z]+\[Delta][z])+q \[Delta][w],k/(z-w) (\[CurlyPhi][z]+\[Delta][z]+p \[Delta][z]),g[z] (\[CurlyPhi][z]+\[Delta][z]+p \[Delta][z])},IsFundField]
NoneTrue[{(E^\[CurlyPhi])[z],(E^(a \[CurlyPhi]))[z],k/(z-w) +\[CurlyPhi][z],k/(z-w),1},IsFundField]

(* IsExpField *)
AllTrue[{(E^\[CurlyPhi])[z],(E^(\[Lambda] \[CurlyPhi]))[z],(E^(\[Lambda] \[CurlyPhi]+\[Mu] \[Delta]))[z],(E^(\[Lambda] (\[CurlyPhi]+\[Delta])))[z],(E^((\[Lambda]+1) (\[CurlyPhi]+\[Delta])))[z],(E^((\[Lambda]+1) (\[CurlyPhi]+\[Delta])+\[CurlyPhi]))[z],(E^((\[Lambda]+1) (\[CurlyPhi]+\[Delta])+(\[Mu]+\[Rho])(\[CurlyPhi])))[z],(E^(z \[CurlyPhi]))[z],(E^((z+w) \[CurlyPhi]))[z]},IsExpField]
NoneTrue[{\[CurlyPhi][z],Derivative[1][\[CurlyPhi]][z],\[CurlyPhi][z](E^\[CurlyPhi])[z],\[CurlyPhi][z]+(E^\[CurlyPhi])[z],(E^(\[CurlyPhi]+k))[z],(E^(\[CurlyPhi]+1/(z-w)))[z]},IsExpField]


(* ::Input::Initialization:: *)
IsVertexField[f_]:=Module[{pattern},
pattern=Table[{
VertexfieldNames[[i]][z_]:>True,
\!\(\*SuperscriptBox[\(VertexfieldNames\[LeftDoubleBracket]i\[RightDoubleBracket]\), 
TagBox[
RowBox[{"(", "n_", ")"}],
Derivative],
MultilineFunction->None]\)[z_]:>True,
\[Lambda]_ VertexfieldNames[[i]][z_]:>True,
\[Lambda]_ \!\(\*SuperscriptBox[\(VertexfieldNames\[LeftDoubleBracket]i\[RightDoubleBracket]\), 
TagBox[
RowBox[{"(", "n_", ")"}],
Derivative],
MultilineFunction->None]\)[z_]:>True,
a_. e1_[z_]+e2_:>(IsVertexField[e1[z]]||IsVertexField[a])&&IsVertexField[e2]
},
{i,Length[VertexfieldNames]}]//Flatten;

(f//Expand)/.pattern//TrueQ
];


(* ::Input::Initialization:: *)
(* Extract exponential fields in a list of fields *)
GetExponentialFields[fList_]:=Cases[fList,x_/;IsExpField[x]==True];
GetNonExponentialFields[fList_]:=Cases[fList,x_/;IsExpField[x]==False];


(* ::Input::Initialization:: *)
Clear[MakeOp,Make]

(* Wrap each basic free field f[z] in Op *)
MakeOp[field_]:=((field/.{f_[z_]:>Op[{f[z]}]/;IsFreeField[f[z]]})*Op[{}])//Expand//NOFree//Expand;
Make=MakeOp;



(* ::Input::Initialization:: *)
Clear[MakeField];
(* (\[ExponentialE]^(\[Lambda] \[CurlyPhi]))-->(\[ExponentialE]^(\[Lambda] \[CurlyPhi]))[z], (\[CurlyPhi]^\[Prime])-->(\[CurlyPhi]^\[Prime])[z] *)
(* \[Delta] (\[ExponentialE]^(\[Lambda] \[CurlyPhi]))-->\[Delta][z](\[ExponentialE]^(\[Lambda] \[CurlyPhi]))[z], \[CurlyPhi]^\[Prime](\[ExponentialE]^(\[CurlyPhi]+\[Delta]))-->(\[CurlyPhi]^\[Prime])[z](\[ExponentialE]^(\[CurlyPhi]+\[Delta]))[z] *)
(* !!! it's crucial to have IsFreeField working properly !!! *)
MakeField[exp_][z_]:=(exp/.{f_:>f[z]/;IsFreeField[f[z]]}) 


(* ::Input::Initialization:: *)
d[n_][exp_]:=Module[{z},D[exp//ExpressionToFieldFunction[#][z]&,{z,n}]//FieldFunctionToExpression]


(* ::Input::Initialization:: *)
(* Op[{f[z],g[z],h[w],...}] --> Op[{f[z]}] Op[{g[z]}] Op[{h[w]}] ... *)
SplitOp[o_]:=o//.{Op[{a_,b__}]:>Op[{a}]Op[{b}]};


(* ::Input::Initialization:: *)
(* Op[{...}] to other formats *)

(* Op[{\[CurlyPhi][z],(\[ExponentialE]^\[CurlyPhi])[w]}] --> \[CurlyPhi][z](\[ExponentialE]^\[CurlyPhi])[w]*)
OpToField[o_]:=(o//SplitOp)/.{Op[{f_[z_]}]:>f[z],Op[{}]->1}

(* Op[{\[CurlyPhi][z],(\[ExponentialE]^\[CurlyPhi])[z]}] --> \[CurlyPhi] \[ExponentialE]^\[CurlyPhi]*)
OpToFieldName[o_]:=(o//SplitOp)/.{Op[{f_[z_]}]:>f,Op[{}]->1}

(* Op[{\[CurlyPhi][z],(\[ExponentialE]^(\[CurlyPhi]+\[Delta]))[w]}] --> \[CurlyPhi][z]\[ExponentialE]^(\[CurlyPhi][w]+\[Delta][w]) *)
OpToFieldFn[o_]:=(o//SplitOp)/.{Op[{f_[z_]}]:>ExpressionToFieldFunction[f][z],Op[{}]->1}


(* ::Input::Initialization:: *)
(* \[CurlyPhi] \[Delta] (\[ExponentialE]^\[Delta]) --> \[CurlyPhi][z]\[Delta][z]\[ExponentialE]^\[Delta][z] *)
(* Thsi is different from MakeField which maps (\[ExponentialE]^\[Delta])-->(\[ExponentialE]^\[Delta])[z] *)
ExpressionToFieldFunction[exp_][z_]:=exp/.{f_:>f[z]/;IsFundField[f[z]]}

(* \[CurlyPhi][z]\[Delta][z](\[ExponentialE]^(\[Delta][z]+\[CurlyPhi][z])) --> \[CurlyPhi] \[Delta] \[ExponentialE]^(\[Delta]+\[CurlyPhi]) *)
FieldFunctionToExpression[fieldFn_]:=fieldFn/.{f_[z_]:>f/;IsFundField[f[z]]}


(* ::Input::Initialization:: *)
(* NOFree[Op[{f1[z],f2[z],... }] * Op[{f3[w],f4[w],...}]] = NOFree[Op[{f1[z], f2[z], f3[w], f4[w], ...}]] *)
(* NO acts linearly on the arguments *)
(* NOFree[a Op[l1]Op[l2] + b Op[l3]] = a NOFree[Op[l1]Op[l2]] + b NOFree[Op[l3]], etc. *)

Clear[NOFree]

NOFree[op_]:=Module[{ReOrdering},

ReOrdering[fList_]:=fList//.{
{x___,y_,z_,u___}:>{x,z,y,u}/;IsFundField[z]&&IsExpField[y],
{x___,y_,z_,u___}:>{x}~Join~Sort[{y,z}]~Join~{u}/;IsExpField[y]&&IsExpField[z] (* exponential fields are sorted by the built-in Sort *)
}//.{{x___,y_,z_,u___}:>{x,z,y,u}/;(Difficulty[y]>Difficulty[z])&&IsFundField[y]&&IsFundField[z]}
;
(op//Expand)//.{Op[l1_]Op[l2_]:>Op[l1~Join~l2],Op[l_]^n_:>Op[Table[l,{i,n}]//Flatten]}/.{Op[l_]:>Op[l//ReOrdering]}
];
NOfree=NOFree;



(* ::Input::Initialization:: *)
Clear[Origin,Difficulty];

(* Input: A free field \[Delta][z], ((\[Beta]^\[Prime])^\[Prime])[z], or (\[ExponentialE]^(a(\[CurlyPhi]+b \[Delta])))[z] *)
(* Return: the origin of the field *)
(* \[Delta][z] \[Rule] \[Delta], ((\[Beta]^\[Prime])^\[Prime])[z] \[Rule] \[Beta], \[ExponentialE]^(a(\[CurlyPhi]+b \[Delta])) \[Rule] a(\[CurlyPhi]+b\[Delta]) *)
Origin[field_]:=Module[{z},
field
/.{x_. f_[z_]:>f/;IsFreeField[f[z]]} (* remove the coordinate dependence *)
/.{x_. Derivative[n_][f_]:>f/;IsFreeField[f[z]],E^x_:>(x//Expand)} (* remove derivatives and exponent *)
]

NumberOfDerivative[field_]:=field/.{x_. Derivative[n_][f_][z_]:>n/;IsFreeField[f[z]],field:>0};

(* measure a the difficulty when dealing with a given non-exponential field *)
(* difficult fields like exponential fields are placed at the end when doing NOfree *)
Difficulty[f_[z_]]:=If[
IsFundField[f[z]],
Position[fieldNames,Origin[f[z]]][[1,1]]+0.01NumberOfDerivative[f[z]]-LetterNumber[ToString[z]]/26,
0];




(* ::Input::Initialization:: *)
Clear[SectorsNumsItBelongsTo,AutoSector];
sectors={};

SectorsProperlySet[]:=(sectors//Flatten//Sort)==(fieldNames//Sort);
AutoSector[]:=Module[{},1;];

(* In principal, a field can belong to multiplet sectors *)
(* But in this version we deal only with the possibility of belonging to one sector *)
(* hence Length[SectorsNumsItBelongsto]\[Equal]1 *)
SectorsNumsItBelongsTo[o1_+o2_]:=(SectorsNumsItBelongsTo[o1]~Join~SectorsNumsItBelongsTo[o2])//DeleteDuplicates//Sort;
SectorsNumsItBelongsTo[a_ o1_]:=SectorsNumsItBelongsTo[o1];

SectorsNumsItBelongsTo[origin_]:=Module[{sectorsItBelongsTo},
(* if varialbe `sectors` is not properly set *)
(* group all fields into one sector *)
If[!SectorsProperlySet[],Return[{1}]];

sectorsItBelongsTo=Cases[sectors,x_/;MemberQ[x,origin]];
Table[Position[sectors,sectorsItBelongsTo[[i]]]//Flatten,{i,Length[sectorsItBelongsTo]}]//Flatten
]/;IsFreeField[origin//MakeField[#][z]&];
SectorsNumsItBelongsTo[o_]:={};



(* ::Input::Initialization:: *)
Clear[Decouple];
Decouple[op_]:=Module[{ops,op0,fields},
op0=op//NOFree;
fields=op0/.{Op->Identity};
ops=Table[
Op[Cases[fields,f_[z_]/;SectorsNumsItBelongsTo[Origin[f[z]]][[1]]==i]]//NOFree,
{i,Length[sectors]}
]
];

DecoupledFactorsNumber[op_]:=DeleteCases[Decouple[op],x_/;x==Op[{}]]//Length




(* ::Input::Initialization:: *)
InitTwoPt[]:=Module[{},
Clear[TwoPt];

TwoPt[Op[{f1_[z_]}],Op[{f2_[w_]}]]:=0 (* define only the non-zero 2pt functions below *);
TwoPt[o1_+o2_,o3_]:=TwoPt[o1,o3]+TwoPt[o2,o3];
TwoPt[o1_,o2_+o3_]:=TwoPt[o1,o2]+TwoPt[o1,o3];
TwoPt[coeff1_. Op[l1_],coeff2_. Op[l2_]]:=coeff1 coeff2 TwoPt[Op[l1],Op[l2]];

(* -- Behavior with derivatives *)
TwoPt[Op[{f1_[z_]}],Op[{D[f2_[w_],{w_,m_}]}]]:=D[TwoPt[Op[{f1[z]}],Op[{f2[w]}]],{w,m}];
TwoPt[Op[{D[f1_[z_],{z_,n_}]}],Op[{f2_[w_]}]]:=D[TwoPt[Op[{f1[z]}],Op[{f2[w]}]],{z,n}];
TwoPt[Op[{D[f1_[z_],{z_,n_}]}],Op[{D[f2_[w_],{w_,m_}]}]]:=D[TwoPt[Op[{f1[z]}],Op[{f2[w]}]],{z,n},{w,m}];

(* -- Twopt with exponential field *)

TwoPt[Op[{(E^f1_)[z_]}],Op[{(E^f2_)[w_]}]]:=E^TwoPt[f1//MakeField[#][z]&//Make,f2//MakeField[#][w]&//Make]/;IsFundField[f1//MakeField[#][z]&]&&IsFundField[f2//MakeField[#][z]&];
TwoPt[Op[{(E^f1_)[z_]}],Op[{f2_[w_]}]]:=TwoPt[f1//MakeField[#][z]&//Make,f2//MakeField[#][w]&//Make]/;IsFundField[f1//MakeField[#][z]&]&&IsFundField[f2[w]];
TwoPt[Op[{f1_[z_]}],Op[{(E^f2_)[w_]}]]:=TwoPt[f1//MakeField[#][z]&//Make,f2//MakeField[#][w]&//Make]/;IsFundField[f1[z]]&&IsFundField[f2//MakeField[#][z]&]
];


InitTwoPt[]

(* ======\[Equal] Unittests ======\[Equal] *)
fieldNames={\[CurlyPhi],\[Delta]};
TwoPt[Op[{\[CurlyPhi][z_]}],Op[{\[CurlyPhi][w_]}]]:=\[CurlyPhi]\[CurlyPhi] Log[z-w];
TwoPt[Op[{\[Delta][z_]}],Op[{\[Delta][w_]}]]:=\[Delta]\[Delta] Log[z-w];

{
TwoPt[Op[{\[CurlyPhi][z]}]+Op[{\[CurlyPhi][z]}],Op[{\[CurlyPhi][w]}]]==2\[CurlyPhi]\[CurlyPhi] Log[z-w],
TwoPt[Op[{\[CurlyPhi][z]}]+Op[{\[CurlyPhi][z]}],Op[{Derivative[1][\[CurlyPhi]][w]}]]==2D[\[CurlyPhi]\[CurlyPhi] Log[z-w],w],
TwoPt[Op[{\[CurlyPhi][z]}],Op[{Derivative[1][\[CurlyPhi]][w]}]]==D[\[CurlyPhi]\[CurlyPhi] Log[z-w],w],
TwoPt[Op[{Derivative[1][\[CurlyPhi]][z]}],Op[{Derivative[1][\[CurlyPhi]][w]}]]==D[\[CurlyPhi]\[CurlyPhi] Log[z-w],{z,1},{w,1}],


TwoPt[Op[{\[CurlyPhi][z]}],Op[{(E^\[CurlyPhi])[w]}]]==\[CurlyPhi]\[CurlyPhi] Log[z-w],
TwoPt[Op[{\[CurlyPhi][z]}],Op[{(E^(\[CurlyPhi]+\[Delta]))[w]}]]==\[CurlyPhi]\[CurlyPhi] Log[z-w],
TwoPt[Op[{\[CurlyPhi][z]}],Op[{(E^(\[Delta]-\[CurlyPhi]))[w]}]]==-\[CurlyPhi]\[CurlyPhi] Log[z-w],
TwoPt[Op[{Derivative[1][\[CurlyPhi]][z]}],Op[{(E^(\[Delta]-\[CurlyPhi]))[w]}]]==D[-\[CurlyPhi]\[CurlyPhi] Log[z-w],z],
TwoPt[Op[{\[CurlyPhi][z]}]+Op[{Derivative[1][\[CurlyPhi]][z]}],Op[{(E^(\[Lambda][u]\[CurlyPhi]))[w]}]]==\[Lambda][u]\[CurlyPhi]\[CurlyPhi] Log[z-w]+D[\[CurlyPhi]\[CurlyPhi] \[Lambda][u]Log[z-w],z],
TwoPt[Op[{Derivative[1][\[CurlyPhi]][z]}],Op[{(E^(3(\[Delta]-\[CurlyPhi])))[w]}]]==D[-3\[CurlyPhi]\[CurlyPhi] Log[z-w],z],
TwoPt[Op[{\[CurlyPhi][z]}],Op[{(E^(\[Lambda] \[CurlyPhi]))[w]}]]==\[Lambda] \[CurlyPhi]\[CurlyPhi] Log[z-w],
TwoPt[Op[{Derivative[1][\[CurlyPhi]][z]}],Op[{(E^\[CurlyPhi])[w]}]]==D[\[CurlyPhi]\[CurlyPhi] Log[z-w],z],
TwoPt[Op[{Derivative[1][\[CurlyPhi]][z]}],Op[{(E^(\[Lambda] \[CurlyPhi]))[w]}]]==D[\[Lambda] \[CurlyPhi]\[CurlyPhi] Log[z-w],z],
TwoPt[Op[{Derivative[1][\[CurlyPhi]][z]}],Op[{(E^(\[Lambda] \[CurlyPhi]+\[Mu] \[Delta]))[w]}]]==D[\[Lambda] \[CurlyPhi]\[CurlyPhi] Log[z-w],z],

TwoPt[Op[{(E^\[CurlyPhi])[z]}],Op[{(E^\[CurlyPhi])[w]}]]==E^(\[CurlyPhi]\[CurlyPhi] Log[z-w]),
TwoPt[Op[{(E^(\[Lambda] \[CurlyPhi]))[z]}],Op[{(E^(\[Mu] \[CurlyPhi]))[w]}]]==E^(\[Lambda] \[Mu] \[CurlyPhi]\[CurlyPhi] Log[z-w]),

TwoPt[Op[{(E^(\[Lambda]1 \[CurlyPhi]+\[Mu]1 \[Delta]))[z]}],Op[{(E^(\[Lambda]2 \[CurlyPhi]+\[Mu]2 \[Delta]))[w]}]]==E^(\[Lambda]1 \[Lambda]2 \[CurlyPhi]\[CurlyPhi] Log[z-w]+\[Mu]1 \[Mu]2 \[Delta]\[Delta] Log[z-w]),
TwoPt[Op[{(E^(a \[CurlyPhi]+b \[Delta]))[z]}],Op[{(E^(cc \[CurlyPhi]+dd \[Delta]))[w]}]]==E^(a cc \[CurlyPhi]\[CurlyPhi] Log[z-w]+b dd \[Delta]\[Delta] Log[z-w]),
TwoPt[Op[{(E^(\[CurlyPhi]+\[Delta]))[z]}],Op[{(E^(\[Lambda]2 \[CurlyPhi]+\[Mu]2 \[Delta]))[w]}]]==E^(\[Lambda]2 \[CurlyPhi]\[CurlyPhi] Log[z-w]+\[Mu]2 \[Delta]\[Delta] Log[z-w]),
TwoPt[Op[{(E^(\[Lambda]( \[CurlyPhi]+\[Rho] \[Delta])))[z]}],Op[{(E^(\[Lambda]2 \[CurlyPhi]+\[Mu]2 \[Delta]))[w]}]]==E^(\[Lambda] \[Lambda]2 \[CurlyPhi]\[CurlyPhi] Log[z-w]+\[Lambda] \[Mu]2 \[Rho] \[Delta]\[Delta] Log[z-w])
}



(* ::Input::Initialization:: *)
(* Return ONE with one/many fields contractions *)
(* Contraction takes two Op objects as input *)
(* e.g. FullContraction[Op[{\[CurlyPhi][z]}],Op[{\[CurlyPhi][w],\!\(
\*SubscriptBox[\(\[PartialD]\), \(w\)]\(\[CurlyPhi][w]\)\)}]],
   or,
   FullContraction[Op[{\[CurlyPhi][z], (\[ExponentialE]^(-\[Delta]-\[CurlyPhi]))[z]}],Op[{\!\(
\*SubscriptBox[\(\[PartialD]\), \(w\)]\(\[CurlyPhi][w]\)\)}]] *)
(* will produce (non-empty) contraction of the one field with the other product of fields *)

(* ======\[Equal] Define Contraction ======\[Equal] *)
Clear[Contraction]

(* -- Initializing *)
(* -- no self-contraction *)
Contraction[Op[{f1_[z_]}],Op[{f2_[z_]}]]:=0;

(* -- Contraction between two fields *)
(* Contractions are between an operator with a fundamental operator *)
(* There is no contraction between two exponential operators; *)
(* they will however contribute a multiplicative factor in FullContraction *)
Contraction[Op[{f1_[z_]}],Op[{f2_[w_]}]]:=(
TwoPt[Op[{f1[z]}],Op[{f2[w]}]]
Op[{}~Join~If[IsExpField[f1[z]],{f1[z]},{}]~Join~If[IsExpField[f2[w]],{f2[w]},{}]]
*If[IsExpField[f1[z]]&&IsExpField[f2[w]],0,1]
)

(* -- Contraction between non-exp field f[z] and Subscript[f, 1][w]Subscript[f, 2][w]... *)
Contraction[Op[{f_[z_]}],Op[fList_]]:=(
Sum[Contraction[Op[{f[z]}],Op[{fList[[ii]]}]]Op[Drop[fList,{ii}]],{ii,1,Length[fList]}]
)/;IsFundField[f[z]]

(* -- Contraction between Subscript[f, 1][z]Subscript[f, 2][z] and a non-exp field f[w]... *)
Contraction[Op[fList_],Op[{f_[w_]}]]:=(
Sum[Contraction[Op[{fList[[ii]]}],Op[{f[w]}]]Op[Drop[fList,{ii}]],{ii,1,Length[fList]}]
)/;IsFundField[f[w]];

(* -- Contraction between an exp field f[z] and Subscript[f, 1][w]Subscript[f, 2][w]... *)
Contraction[Op[{f_[z_]}],Op[fList_]/;Length[fList]>1]:=Module[{
uselessFactor,
fListWithLabels,RemoveLabels,exponentialFields,nonExponentialFields,
possibleContractedWithLabels,result
},
exponentialFields=Cases[fList,x_/;IsExpField[x]==True];
nonExponentialFields=DeleteCases[fList,x_/;IsExpField[x]];

(* First kick out factors in fList having 0 two-pt with the exponential op f[z] *)
uselessFactor={};
uselessFactor=Cases[fList,x_/;TrueQ[TwoPt[Op[{x}],Op[{f[z]}]]==0]];
nonExponentialFields=DeleteCases[nonExponentialFields,x_/;MemberQ[uselessFactor,x]];

(* add labels to tell the difference between non-exponential fields with the same names *)
fListWithLabels=Table[{nonExponentialFields[[i]],i},{i,Length[nonExponentialFields]}];
RemoveLabels[listWithLabels_]:=Table[listWithLabels[[i]][[1]],{i,Length[listWithLabels]}];

(* Subsets[fListWithLabels] collects all possible combinations of fields *)
(* that are to be contracted with the exponential field *)

(* remove empty contraciton *)
possibleContractedWithLabels=DeleteCases[Subsets[fListWithLabels],{}];

(* contracted exponential field in fList should be kept *)
result=Op[exponentialFields]Op[uselessFactor]Sum[
Product[
TwoPt[Op[{f[z]}],Op[{possibleContractedWithLabels[[c]][[j]][[1]]}]],
{j,1,Length[possibleContractedWithLabels[[c]]]}
]
Op[RemoveLabels[Complement[fListWithLabels,DeleteCases[possibleContractedWithLabels[[c]],x_/;IsExpField[x[[1]]]==True]]]]Op[{f[z]}]
,{c,1,Length[possibleContractedWithLabels]}
]
]/;IsExpField[f[z]];


(* -- Contraction between Subscript[f, 1][z]Subscript[f, 2][z] with an exp field f[w]... *)
Contraction[Op[fList_]/;Length[fList]>1,Op[{f_[w_]}]]:=Module[{
uselessFactor,
exponentialFields,nonExponentialFields,
fListWithLabels,RemoveLabels,
possibleContractedWithLabels,result
},
exponentialFields=GetExponentialFields[fList];
nonExponentialFields=GetNonExponentialFields[fList];

(* First kick out factors in fList having 0 two-pt with the exponential op f[z] *)
uselessFactor={};
uselessFactor=Cases[fList,x_/;TrueQ[TwoPt[Op[{x}],Op[{f[w]}]]==0]];
nonExponentialFields=DeleteCases[nonExponentialFields,x_/;MemberQ[uselessFactor,x]];

(* add labels to tell the difference between non-exponential fields with the same names *)
fListWithLabels=Table[{nonExponentialFields[[i]],i},{i,Length[nonExponentialFields]}];
RemoveLabels[listWithLabels_]:=Table[listWithLabels[[i]][[1]],{i,Length[listWithLabels]}];

(* Subsets[fListWithLabels] collects all possible combinations of fields *)
(* that are to be contracted with the exponential field *)

(* remove empty contraciton *)
possibleContractedWithLabels=DeleteCases[Subsets[fListWithLabels],{}];

(* contracted exponential field in fList should be kept *)
result=(Sum[(* sum over all possible ways of contractions (collected in possibleContractedWithLabels) *)
Product[TwoPt[Op[{possibleContractedWithLabels[[c]][[j]][[1]]}],Op[{f[w]}]],{j,1,Length[possibleContractedWithLabels[[c]]]}]
Op[RemoveLabels[Complement[fListWithLabels,DeleteCases[possibleContractedWithLabels[[c]],x_/;IsExpField[x[[1]]]==True]]]]
,{c,1,Length[possibleContractedWithLabels]}]
If[Length[exponentialFields]>0,Op[exponentialFields],1])
Op[{f[w]}](* after contraction, the exponential field is reinstated *)
]/;IsExpField[f[w]];




(* ::Input::Initialization:: *)
Clear[IsCoupled];
IsCoupled[f1_[z_],f2_[w_]]:=!TrueQ[TwoPt[Origin[f1[z]]// MakeField[#][z]&//Make,Origin[f2[w]]//MakeField[#][w]&//Make]==0];




(* ::Input::Initialization:: *)
counter=0;
(* FullContraction[] takes two Op objects as arguments *)
(* e.g. FullContraction[Op[{\[CurlyPhi][z],\!\(
\*SubscriptBox[\(\[PartialD]\), \(z\)]\(\[CurlyPhi][z]\)\)}],Op[{\[CurlyPhi][w],\!\(
\*SubscriptBox[\(\[PartialD]\), \(w\)]\(\[CurlyPhi][w]\)\)}]] *)

Clear[FullContraction,Op,OP]

OP=Op;
Op[{(E^(\[Lambda]_(e1_+e2_)))[z_]}]:=Op[{(E^(\[Lambda] e1+\[Lambda] e2))[z]}];

(* Impose linearity *)
FullContraction[0,o_]:=0;
FullContraction[o_,0]:=0;
FullContraction[a_ Op[list_],o_]:=a  FullContraction[Op[list],o];
FullContraction[o_,a_ Op[list_]]:=a  FullContraction[o,Op[list]];
FullContraction[o1_+o2_,o3_]:=FullContraction[o1,o3]+FullContraction[o2,o3];
FullContraction[o1_,o2_+o3_]:=FullContraction[o1,o2]+FullContraction[o1,o3];

FullContraction[Op[{}],o_]:=(o);
FullContraction[o_,Op[{}]]:=(o);

FullContraction[Op[{f1_[z_]}],Op[{f2_[w_]}]]:=(Contraction[Op[{f1[z]}],Op[{f2[w]}]]+ Op[{f1[z],f2[w]}])If[IsExpField[f1[z]]&&IsExpField[f2[w]],TwoPt[Op[{f1[z]}],Op[{f2[w]}]],1];


FullContraction[o1_,o2_]:=Module[{result,o1decoupled,o2decoupled},
o1decoupled=Decouple[o1];
o2decoupled=Decouple[o2];
Product[FullContraction[o1decoupled[[i]],o2decoupled[[i]]],{i,Length[sectors]}]
]/;(SectorsProperlySet[]&&DecoupledFactorsNumber[o1]>1&&DecoupledFactorsNumber[o2]>1);


FullContraction[Op[fList1_],Op[fList2_]]:=Module[{result,noContraction,nonZeroContraction,contributingFactors},
(* Select the last field factor fList\[LeftDoubleBracket]-1\[RightDoubleBracket] from the 1st op (Op1); *)

(* fList\[LeftDoubleBracket]-1\[RightDoubleBracket] eithers participates in NO contraction with the 2nd op (Op2) at all *)
(* and therefore will be stipped off as a bystander in the last line *)
(* (if it's an exponential field, it still will generate multiplicative factors of its 2-pt function 
 with the exponential ops in Op2) *)

noContraction=
+(If[fList1[[-1]]//IsExpField,

Product[TwoPt[Op[{GetExponentialFields[fList2][[i]]}],Op[{fList1[[-1]]}]],{i,Length@GetExponentialFields[fList2]}],
1
]
*FullContraction[Op[Drop[fList1,{-1}]],Op[fList2]]
*Op[{fList1[[-1]]}]) (* bystander *);

(* or participate in contraction with the 2nd op (Op2) *)
contributingFactors=Cases[fList2,x_/;IsCoupled[fList1[[-1]],x]];
If[Length[contributingFactors]==0,Return[noContraction]];

counter=counter+1;
nonZeroContraction=(
FullContraction[
(* the rest of fList1 *)
Op[Drop[fList1,{-1}]],
(* an exponential fList1\[LeftDoubleBracket]-1\[RightDoubleBracket] should be first removed from its contraction with fList2,
   then the result of contraction does FullContraction with the rest of fList1 *)
(Contraction[Op[{fList1[[-1]]}],Op[fList2]]//SplitOp)*If[IsExpField[fList1[[-1]]],Op[{fList1[[-1]]}]^-1 Op[{}],1]//NOfree]
If[IsExpField[fList1[[-1]]],Op[{fList1[[-1]]}],1](* the exponential fList1\[LeftDoubleBracket]-1\[RightDoubleBracket] is reinstated outside *)
);

result=(noContraction+nonZeroContraction);
result//NOFree

]/;Length[fList1]>=2&&Length[fList2]>=1;

FullContraction[Op[fList1_],Op[fList2_]]:=Module[{result,noContraction,nonZeroContraction,contributingFactors},

(* Select the last field factor fList2\[LeftDoubleBracket]-1\[RightDoubleBracket] from the 2nd op (Op2); *)

(* fList2\[LeftDoubleBracket]-1\[RightDoubleBracket] could choose to participate in no contraction at all, *)
(*Print["B"];*)
noContraction=(If[fList2[[-1]]//IsExpField,
(* if fList2\[LeftDoubleBracket]-1\[RightDoubleBracket] is an exponential field, *)
(* it still will generate multiplicative factors of its 2-pt function *)
(* with the exponential ops in Op2 *)
Product[TwoPt[Op[{GetExponentialFields[fList1][[i]]}],Op[{fList2[[-1]]}]],{i,Length@GetExponentialFields[fList1]}],
1
]FullContraction[Op[fList1],Op[Drop[fList2,{-1}]]]Op[{fList2[[-1]]}]);


(* or participate in contraction with the 1st op (Op1) *)
contributingFactors=Cases[fList2,x_/;IsCoupled[fList1[[-1]],x]];
If[contributingFactors=={},Return[noContraction]];


counter=counter+1;
nonZeroContraction=(
FullContraction[
(* an exponential fList2\[LeftDoubleBracket]-1\[RightDoubleBracket] should be first removed from its contraction with fList1,
   then the result of contraction does FullContraction with the rest of fList2 *)
(Contraction[Op[fList1],Op[{fList2[[-1]]}]]//SplitOp)*If[IsExpField[fList2[[-1]]],Op[{fList2[[-1]]}]^-1 Op[{}],1]//NOFree,
(* the rest of fList2 *)
Op[Drop[fList2,{-1}]]]
If[IsExpField[fList2[[-1]]],Op[{fList2[[-1]]}],1](* the exponential fList2\[LeftDoubleBracket]-1\[RightDoubleBracket] is reinstated outside *)
);

result=noContraction+nonZeroContraction;
result//NOFree
]/;Length[fList2]>=2&&Length[fList1]>=1;


(* ========================\[Equal] *)
(* ======\[Equal] Unittests ======\[Equal] *)
(*

InitTwoPt[]
fieldNames={\[CurlyPhi],\[Delta]};
sectors={{\[CurlyPhi],\[Delta]}};
Clear[\[CurlyPhi]\[CurlyPhi],\[Delta]\[Delta]];
TwoPt[Op[{\[CurlyPhi][z_]}],Op[{\[CurlyPhi][w_]}]]:=\[CurlyPhi]\[CurlyPhi][z-w]
TwoPt[Op[{\[Delta][z_]}],Op[{\[Delta][w_]}]]:=\[Delta]\[Delta][z-w]


{FullContraction[Op[{(\[ExponentialE]^\[Delta])[z]}],Op[{(\[ExponentialE]^\[Delta])[w]}]]\[Equal]\[ExponentialE]^\[Delta]\[Delta][z-w]Op[{(\[ExponentialE]^\[Delta])[z],(\[ExponentialE]^\[Delta])[w]}]//NOfree,
FullContraction[Op[{(\[ExponentialE]^\[Delta])[z],(\[Delta]^\[Prime])[z]}],Op[{(\[ExponentialE]^\[Delta])[w]}]]\[Equal]\[ExponentialE]^\[Delta]\[Delta][z-w](D[\[Delta]\[Delta][z-w],z]Op[{(\[ExponentialE]^\[Delta])[z],(\[ExponentialE]^\[Delta])[w]}]+Op[{(\[ExponentialE]^\[Delta])[z],(\[Delta]^\[Prime])[z],(\[ExponentialE]^\[Delta])[w]}])//NOfree,
FullContraction[Op[{(\[ExponentialE]^\[Delta])[z],\[Delta][z],\[Delta][z]}],Op[{(\[ExponentialE]^\[Delta])[w]}]]\[Equal]\[ExponentialE]^\[Delta]\[Delta][z-w](\[Delta]\[Delta][z-w]^2Op[{(\[ExponentialE]^\[Delta])[z],(\[ExponentialE]^\[Delta])[w]}]+2\[Delta]\[Delta][z-w]Op[{(\[ExponentialE]^\[Delta])[z],(\[ExponentialE]^\[Delta])[w],\[Delta][z]}]+Op[{(\[ExponentialE]^\[Delta])[z],\[Delta][z],\[Delta][z],(\[ExponentialE]^\[Delta])[w]}])//NOfree,
FullContraction[Op[{(\[ExponentialE]^\[Delta])[z],(\[ExponentialE]^\[Delta])[z]}],Op[{\[Delta][w]}]]\[Equal]2\[Delta]\[Delta][z-w]Op[{(\[ExponentialE]^\[Delta])[z],(\[ExponentialE]^\[Delta])[z]}]+Op[{(\[ExponentialE]^\[Delta])[z],(\[ExponentialE]^\[Delta])[z],\[Delta][w]}]//NOFree
}

InitTwoPt[]
fieldNames={\[Beta],\[Gamma],\[CurlyPhi],\[Delta]};
sectors={{\[Beta],\[Gamma]},{\[CurlyPhi],\[Delta]}};
Clear[\[CurlyPhi]\[CurlyPhi],\[Delta]\[Delta]];
TwoPt[Op[{\[CurlyPhi][z_]}],Op[{\[CurlyPhi][w_]}]]:=\[CurlyPhi]\[CurlyPhi][z-w]
TwoPt[Op[{\[Delta][z_]}],Op[{\[Delta][w_]}]]:=\[Delta]\[Delta][z-w]
TwoPt[Op[{\[Beta][z_]}],Op[{\[Gamma][w_]}]]:=\[Beta]\[Gamma][z-w]

{
FullContraction[Op[{\[Beta][z]}],Op[{\[Gamma][w]}]]\[Equal]\[Beta]\[Gamma][z-w]Op[{}]+Op[{\[Beta][z],\[Gamma][w]}]//NOfree,
FullContraction[Op[{\[Beta][z],\[CurlyPhi][z]}],Op[{\[Gamma][w],\[CurlyPhi][w]}]]\[Equal](\[Beta]\[Gamma][z-w]Op[{}]+Op[{\[Beta][z],\[Gamma][w]}])(Op[{\[CurlyPhi][z],\[CurlyPhi][w]}]+\[CurlyPhi]\[CurlyPhi][z-w]Op[{}])//NOfree
}*)


(* ::Input::Initialization:: *)
(* compute the OPE coefficient of (z-w)^order between exp1 and exp2 *)
(* e.g. OPEfreeCoefficient[\[Gamma] \[Gamma]^\[Prime],\[Beta]] *)
Clear[OPEfree,OPEFree,OPEfreeCoefficient,OPEFreeCoefficient]

OPEfreeCoefficient[exp1_,exp2_][order_]:=Module[{z,w},
(FullContraction[
exp1//MakeField[#][z]&//Make//NOFree,
exp2//MakeField[#][w]&//Make//NOFree
]//OpToFieldFn//SeriesCoefficient[#,{z,w,order}]&)//FieldFunctionToExpression//OpToFieldName//Expand];
OPEFreeCoefficient=OPEfreeCoefficient;

OPEfree[exp1_,exp2_][z_,w_][order_:0]:=Module[{},
FullContraction[
exp1//MakeField[#][z]&//Make//NOFree,
exp2//MakeField[#][w]&//Make//NOFree
]//OpToFieldFn//Simplify//Series[#,{z,w,order}]&//Normal//FieldFunctionToExpression//MakeField[#][w]&
];
OPEFree=OPEfree;



(* ::Input::Initialization:: *)
Clear[NOCofOp];
(* OPE[o1[z],o2[w]] = SingularOPEs + NOCofOp[o1[z],o2[w]][z,w] + O[z-w] *)
NOCofOp[o1_+o2_,o3_][z_,w_]:=NOCofOp[o1,o3][z,w]+NOCofOp[o2,o3][z,w];
NOCofOp[o1_,o2_+o3_][z_,w_]:=NOCofOp[o1,o2][z,w]+NOCofOp[o1,o3][z,w];

NOCofOp[f_. Op[l1_],g_. Op[l2_]][z_,w_]:=f g FullContraction[Op[l1],Op[l2]]//OpToFieldFn//SeriesCoefficient[#,{z,w,0}]&//FieldFunctionToExpression;

Clear[NOC]

(* NOC[o1,o2] = (o1 o2) *)
NOC[exp1_,exp2_]:=Module[{field1,field2,z,w,op1,op2},
field1=exp1//MakeField[#][z]&;
field2=exp2//MakeField[#][w]&;
op1=field1//MakeOp;
op2=field2//MakeOp;
NOCofOp[op1,op2][z,w]//SplitOp//OpToFieldName
]



(* ::Input::Initialization:: *)
Clear[PB]
PB[ff_,gg_]:=Sum[\[CapitalOmega]PB[[i,j]]D[ff,coord[[i]]]D[gg,coord[[j]]],{i,Length[coord]},{j,Length[coord]}]

